import * as THREE from 'three';
export function createBoron11() {
  const group = new THREE.Group();
  
  // Boron-11 Isotope & Nuclear Spin (NMR)
  
  const core = new THREE.Group();
  group.add(core);
  
  const protonMat = new THREE.MeshPhysicalMaterial({color: 0xff0000, metalness: 0.3, roughness: 0.1, clearcoat: 1.0});
  const neutronMat = new THREE.MeshPhysicalMaterial({color: 0xffffff, metalness: 1.0, roughness: 0.2});
  
  const particles = [];
  // B-11: 5 Protons, 6 Neutrons
  for(let i=0; i<11; i++) {
      const isProton = i < 5;
      const mesh = new THREE.Mesh(new THREE.SphereGeometry(0.5, 64, 64), isProton ? protonMat : neutronMat);
      
      const pos = new THREE.Vector3(
          (Math.random()-0.5)*1.5,
          (Math.random()-0.5)*1.5,
          (Math.random()-0.5)*1.5
      );
      mesh.position.copy(pos);
      core.add(mesh);
      particles.push({mesh, isProton, pos: pos.clone(), vel: new THREE.Vector3(0,0,0)});
  }
  
  const pLight = new THREE.PointLight(0xffaaaa, 5, 20);
  core.add(pLight);

  // Nuclear Magnetic Spin Axis
  const axis = new THREE.ArrowHelper(new THREE.Vector3(0,1,0), new THREE.Vector3(0,0,0), 4, 0x00ffff, 0.5, 0.5);
  core.add(axis);
  
  // Magnetic field lines (torus wireframes)
  for(let i=1; i<4; i++) {
      const field = new THREE.Mesh(
          new THREE.TorusGeometry(i, 0.1, 8, 32),
          new THREE.MeshBasicMaterial({color: 0x00ffff, wireframe: true, transparent: true, opacity: 0.2})
      );
      field.rotation.x = Math.PI/2;
      core.add(field);
  }

  group.userData.animate = function(delta, time, speed) {
      // The entire nucleus wobbles (precesses) due to its spin!
      group.rotation.x = 0.3; // Tilt
      group.rotation.y = time * speed * 2.0; // Fast spin
      
      // Jitter
      particles.forEach(p => {
          const pull = new THREE.Vector3(0,0,0).sub(p.mesh.position).multiplyScalar(0.1);
          p.vel.add(pull);
          p.vel.x += (Math.random()-0.5)*0.2; p.vel.y += (Math.random()-0.5)*0.2; p.vel.z += (Math.random()-0.5)*0.2;
          p.vel.multiplyScalar(0.8);
          p.mesh.position.add(p.vel);
      });
  };

  return {
    group: group,
    description: "Boron-11 Isotope & Nuclear Spin. About 80% of the Boron on Earth is the 'Boron-11' isotope (5 Protons, 6 Neutrons). Unlike Boron-10, this isotope is incredibly stable and won't detonate when hit by neutrons. However, B-11 has a different superpower: because it has an odd number of protons (5) and an even number of neutrons (6), the entire nucleus has a net 'Nuclear Spin' (Spin 3/2). This means the entire nucleus acts like a tiny bar magnet! Chemists can put B-11 into a giant magnetic MRI machine and use radio waves to map out its exact chemical structure (Nuclear Magnetic Resonance spectroscopy).",
    parts: [
      { name: "Cluster (5 Red, 6 Silver)", material: "Boron-11 Nucleus", function: "The most common and stable form of Boron." },
      { name: "Cyan Arrow", material: "Net Nuclear Spin", function: "The entire nucleus acts as a tiny quantum magnet." },
      { name: "Wireframe Rings", material: "Magnetic Field", function: "Generated by the spinning positive charge." }
    ],
    quizQuestions: [
      { question: "Because Boron-11 has a net 'Nuclear Spin', what incredible technology can chemists use to study it?", options: ["Microscopes", "Nuclear Magnetic Resonance (NMR) Spectroscopy, which is the exact same technology used in hospital MRI machines!", "X-Rays", "Thermometers"], correct: 1, explanation: "If a nucleus has a spin, it acts like a magnet. By putting the sample in a massive magnet and hitting it with radio waves, chemists can 'listen' to the nucleus ring like a bell and map out the entire molecule!" }
    ]
  };
}