import * as THREE from 'three';
export function createHydrogenElectronSpin() {
  const group = new THREE.Group();
  
  const electronGeo = new THREE.SphereGeometry(1, 32, 32);
  const electronMat = new THREE.MeshStandardMaterial({ color: 0x3333ff, metalness: 0.5 });
  const electron = new THREE.Mesh(electronGeo, electronMat);
  group.add(electron);

  // Spin axis arrow
  const dir = new THREE.Vector3(0, 1, 0);
  const origin = new THREE.Vector3(0, -1.5, 0);
  const length = 3;
  const hex = 0xff0000;
  const arrowHelper = new THREE.ArrowHelper(dir, origin, length, hex, 0.5, 0.5);
  group.add(arrowHelper);

  // Magnetic field lines (Torus)
  const torusGeo = new THREE.TorusGeometry(1.5, 0.05, 16, 64);
  const torusMat = new THREE.MeshBasicMaterial({ color: 0x00ffff, transparent: true, opacity: 0.5 });
  const torus = new THREE.Mesh(torusGeo, torusMat);
  torus.rotation.x = Math.PI / 2;
  group.add(torus);

  group.userData.animate = function(delta, time, speed) {
      electron.rotation.y += delta * speed * 5; // fast spin
  };

  return {
    group: group,
    description: "Electron Spin visualization. The intrinsic angular momentum (spin) of the electron creates a tiny magnetic dipole.",
    parts: [
      { name: "Electron", material: "Lepton", function: "Possesses spin +1/2 or -1/2." },
      { name: "Spin Axis", material: "Vector", function: "Direction of angular momentum." },
      { name: "Magnetic Dipole", material: "Field", function: "Generated by the spinning charge." }
    ]
  };
}
