import * as THREE from 'three';
export function createLithiumPhotonEmission() {
  const group = new THREE.Group();
  
  const nuc = new THREE.Mesh(new THREE.SphereGeometry(0.3, 16, 16), new THREE.MeshBasicMaterial({color: 0xff0000}));
  group.add(nuc);

  // Orbitals
  const orb2s = new THREE.Mesh(new THREE.TorusGeometry(2, 0.05, 16, 100), new THREE.MeshBasicMaterial({color: 0xff00ff}));
  orb2s.rotation.x = Math.PI/2;
  const orb3p = new THREE.Mesh(new THREE.TorusGeometry(4, 0.05, 16, 100), new THREE.MeshBasicMaterial({color: 0xffff00}));
  orb3p.rotation.x = Math.PI/2;
  group.add(orb2s, orb3p);

  // Electron
  const e = new THREE.Mesh(new THREE.SphereGeometry(0.3, 16,16), new THREE.MeshBasicMaterial({color: 0xffffff}));
  group.add(e);

  // Emitted Photon (Wave)
  const photon = new THREE.Group();
  const waveGeo = new THREE.BufferGeometry();
  const wavePoints = [];
  for(let i=0; i<=20; i++) {
      wavePoints.push(new THREE.Vector3(i*0.2, Math.sin(i*Math.PI*0.5)*0.3, 0));
  }
  waveGeo.setFromPoints(wavePoints);
  const wave = new THREE.Line(waveGeo, new THREE.LineBasicMaterial({color: 0xff0000, linewidth: 2})); // Red light
  photon.add(wave);
  const head = new THREE.Mesh(new THREE.ConeGeometry(0.2, 0.5, 8), new THREE.MeshBasicMaterial({color: 0xff0000}));
  head.rotation.z = -Math.PI/2;
  head.position.set(4, 0, 0);
  photon.add(head);
  group.add(photon);

  // Flash
  const flash = new THREE.Mesh(new THREE.SphereGeometry(1, 16, 16), new THREE.MeshBasicMaterial({color: 0xffffff, transparent: true, opacity: 0}));
  group.add(flash);

  group.userData.animate = function(delta, time, speed) {
      group.rotation.y = Math.sin(time*speed*0.2)*0.2;
      
      const cycle = (time * speed) % 4;
      
      if (cycle < 1.0) {
          // Resting high
          e.position.set(4, 0, 0);
          photon.visible = false;
          flash.material.opacity = 0;
      } else if (cycle < 1.2) {
          // Drop and emit
          e.position.set(4 - (cycle-1.0)*10, 0, 0); // Quick jump down
          flash.position.copy(e.position);
          flash.material.opacity = 1 - (cycle-1.0)*5;
          photon.position.set(2, 0, 0);
          photon.visible = true;
      } else {
          // Resting low, photon flies away
          e.position.set(2, 0, 0);
          photon.position.set(2 + (cycle-1.2)*6, 0, 0);
      }
  };

  return {
    group: group,
    description: "Photon Emission. What goes up must come down. When an excited electron inevitably falls back to its ground state (from 3p down to 2s, for example), the Law of Conservation of Energy dictates that the extra energy must go somewhere. It is converted into a brand new photon and fired out into space. This is literally how all light in the universe is created!",
    parts: [
      { name: "Yellow to Magenta Orbit", material: "Quantum Decay", function: "The electron falls to a lower energy state." },
      { name: "Red Wave", material: "Emitted Photon", function: "A particle of light created from the lost energy. Its color depends exactly on the height of the fall." }
    ],
    quizQuestions: [
      { question: "Where does the light from a lightbulb or a fire actually come from?", options: ["It is stored inside the atoms and leaks out", "It is created when excited electrons fall back down to lower energy levels, converting their excess energy into photons", "It is generated by the nucleus", "It comes from electrons colliding with each other"], correct: 1, explanation: "Almost all visible light you see (from the sun, fire, LEDs, or neon signs) is the result of photon emission: electrons dropping from high-energy excited states back down to lower-energy ground states." }
    ]
  };
}