import { plastic, aluminum, glass, copper, steel, darkSteel, rubber, chrome, tinted } from '../utils/materials.js';

export function createMachine(THREE) {
    const group = new THREE.Group();
    const parts = [];

    // Custom glowing materials
    const displayGlow = new THREE.MeshStandardMaterial({
        color: 0x00ffcc,
        emissive: 0x00ffcc,
        emissiveIntensity: 0.8,
        transparent: true,
        opacity: 0.9,
    });

    const activeLED = new THREE.MeshStandardMaterial({
        color: 0xff3300,
        emissive: 0xff3300,
        emissiveIntensity: 1.0,
    });
    
    const membraneMat = new THREE.MeshStandardMaterial({
        color: 0xcccccc,
        metalness: 0.8,
        roughness: 0.2,
        transparent: true,
        opacity: 0.85
    });

    // 1. Microphone Body
    const bodyGeo = new THREE.CylinderGeometry(0.8, 0.8, 6, 32);
    const bodyMesh = new THREE.Mesh(bodyGeo, darkSteel);
    bodyMesh.position.set(0, -3, 0);
    group.add(bodyMesh);
    parts.push({
        name: "Main Body Housing",
        description: "Contains the internal circuitry and preamplifier. Built with robust dark steel.",
        material: "Dark Steel",
        function: "Protects sensitive internal components and provides shielding.",
        assemblyOrder: 1,
        connections: ["Preamplifier Board", "Connector Base"],
        failureEffect: "Physical damage to internal components",
        cascadeFailures: ["Signal Loss", "Preamp Failure"],
        originalPosition: { x: 0, y: -3, z: 0 },
        explodedPosition: { x: -3, y: -3, z: 0 },
        mesh: bodyMesh
    });

    // 2. Diaphragm / Membrane
    const diaphragmGeo = new THREE.CylinderGeometry(0.7, 0.7, 0.05, 32);
    const diaphragmMesh = new THREE.Mesh(diaphragmGeo, membraneMat);
    diaphragmMesh.position.set(0, 0, 0);
    group.add(diaphragmMesh);
    parts.push({
        name: "Diaphragm",
        description: "Ultra-thin metallic membrane that vibrates in response to sound pressure waves.",
        material: "Metallic Film",
        function: "Translates acoustic energy into mechanical displacement.",
        assemblyOrder: 5,
        connections: ["Backplate", "Protection Grid"],
        failureEffect: "Loss of sensitivity or complete signal failure",
        cascadeFailures: ["Inaccurate Readings"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: 3, z: 0 },
        mesh: diaphragmMesh
    });

    // 3. Backplate
    const backplateGeo = new THREE.CylinderGeometry(0.65, 0.65, 0.1, 32);
    const backplateMesh = new THREE.Mesh(backplateGeo, copper);
    backplateMesh.position.set(0, -0.15, 0);
    group.add(backplateMesh);
    parts.push({
        name: "Conductive Backplate",
        description: "Fixed conductive plate forming a capacitor with the diaphragm.",
        material: "Copper",
        function: "Maintains a fixed charge; changes in distance from the diaphragm vary the capacitance.",
        assemblyOrder: 4,
        connections: ["Diaphragm", "Preamplifier Board"],
        failureEffect: "Electrical short or capacitance loss",
        cascadeFailures: ["Preamp Overload"],
        originalPosition: { x: 0, y: -0.15, z: 0 },
        explodedPosition: { x: 0, y: -1, z: 2 },
        mesh: backplateMesh
    });

    // 4. Protection Grid / Mesh
    const gridGeo = new THREE.SphereGeometry(0.85, 16, 16, 0, Math.PI * 2, 0, Math.PI / 2);
    const gridMesh = new THREE.Mesh(gridGeo, chrome);
    gridMesh.material.wireframe = true;
    gridMesh.position.set(0, 0, 0);
    group.add(gridMesh);
    parts.push({
        name: "Protection Grid",
        description: "Metallic mesh covering the capsule to protect the delicate diaphragm.",
        material: "Chrome Wireframe",
        function: "Prevents physical damage and reduces wind noise.",
        assemblyOrder: 6,
        connections: ["Main Body Housing"],
        failureEffect: "Exposure of diaphragm to environmental hazards",
        cascadeFailures: ["Diaphragm Rupture"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: 5, z: 0 },
        mesh: gridMesh
    });

    // 5. Preamplifier Board
    const preampGeo = new THREE.BoxGeometry(0.5, 3, 0.1);
    const preampMesh = new THREE.Mesh(preampGeo, glass);
    preampMesh.position.set(0, -3, 0);
    group.add(preampMesh);
    parts.push({
        name: "Preamplifier Circuit Board",
        description: "Converts high impedance signal from the capsule to low impedance.",
        material: "Silicon & Fiberglass",
        function: "Amplifies the micro-voltage generated by the capacitor capsule.",
        assemblyOrder: 3,
        connections: ["Backplate", "Connector Base"],
        failureEffect: "No signal output or high noise floor",
        cascadeFailures: ["System Failure"],
        originalPosition: { x: 0, y: -3, z: 0 },
        explodedPosition: { x: 3, y: -3, z: 0 },
        mesh: preampMesh
    });

    // 6. SPL Display Panel
    const displayGeo = new THREE.PlaneGeometry(1, 1.5);
    const displayMesh = new THREE.Mesh(displayGeo, displayGlow);
    displayMesh.position.set(0, -3, 0.81);
    group.add(displayMesh);
    parts.push({
        name: "Digital SPL Display",
        description: "Real-time read-out of the Sound Pressure Level.",
        material: "Neon LED Matrix",
        function: "Provides direct visual feedback of the acoustic measurements.",
        assemblyOrder: 7,
        connections: ["Main Body Housing", "Preamplifier Circuit Board"],
        failureEffect: "Loss of direct read-out",
        cascadeFailures: [],
        originalPosition: { x: 0, y: -3, z: 0.81 },
        explodedPosition: { x: 0, y: -3, z: 3 },
        mesh: displayMesh
    });

    // 7. Base Connector
    const baseGeo = new THREE.CylinderGeometry(0.5, 0.5, 1, 16);
    const baseMesh = new THREE.Mesh(baseGeo, aluminum);
    baseMesh.position.set(0, -6.5, 0);
    group.add(baseMesh);
    parts.push({
        name: "XLR Base Connector",
        description: "Standard 3-pin XLR connector for balanced signal output.",
        material: "Aluminum",
        function: "Interfaces the microphone with external recording or analysis equipment.",
        assemblyOrder: 2,
        connections: ["Preamplifier Circuit Board"],
        failureEffect: "Intermittent connection or complete signal loss",
        cascadeFailures: ["Phantom Power Loss"],
        originalPosition: { x: 0, y: -6.5, z: 0 },
        explodedPosition: { x: 0, y: -8, z: 0 },
        mesh: baseMesh
    });

    // Description
    const description = "The Acoustical SPL (Sound Pressure Level) Microphone is a precision measurement instrument designed for acoustic analysis. It employs a capacitive (condenser) capsule with a highly sensitive diaphragm to convert varying sound pressure waves into an electrical signal. Key features include a robust preamplifier for signal conditioning and a digital neon display for real-time SPL monitoring.";

    // Quiz Questions
    const quizQuestions = [
        {
            question: "What is the primary function of the diaphragm in a condenser SPL microphone?",
            options: [
                "To amplify the electrical signal.",
                "To translate acoustic energy into mechanical displacement.",
                "To provide shielding against electromagnetic interference.",
                "To measure the temperature of the air."
            ],
            correct: 1,
            explanation: "The diaphragm vibrates in response to sound pressure waves, altering the distance to the backplate and changing the capacitance, which translates acoustic energy into mechanical movement and subsequently an electrical signal.",
            difficulty: "Medium"
        },
        {
            question: "Why is a preamplifier circuit necessary in this microphone?",
            options: [
                "To convert the high-impedance signal from the capsule to a usable low-impedance signal.",
                "To generate sound waves for calibration.",
                "To power the glowing display panel.",
                "To protect the capsule from physical damage."
            ],
            correct: 0,
            explanation: "Condenser capsules naturally produce a very high-impedance output that cannot travel across standard cables without massive signal loss. The preamplifier converts this to a low-impedance signal.",
            difficulty: "Hard"
        },
        {
            question: "What forms the capacitor in this microphone's capsule?",
            options: [
                "The Main Body Housing and the Protection Grid.",
                "The Preamplifier Board and the XLR Connector.",
                "The Diaphragm and the Conductive Backplate.",
                "The SPL Display and the internal wiring."
            ],
            correct: 2,
            explanation: "The condenser (capacitor) capsule consists of a moving conductive diaphragm and a fixed conductive backplate. Sound waves change the distance between them, thus altering capacitance.",
            difficulty: "Easy"
        }
    ];

    // Animation loop
    const animate = (time, speed, meshes) => {
        // Find meshes by part name
        const diaphragm = meshes.find(m => m.name === "Diaphragm")?.mesh;
        const display = meshes.find(m => m.name === "Digital SPL Display")?.mesh;
        const grid = meshes.find(m => m.name === "Protection Grid")?.mesh;

        if (diaphragm) {
            // High frequency vibration representing sound waves hitting the diaphragm
            const displacement = Math.sin(time * speed * 20) * 0.05;
            diaphragm.position.y = displacement;
        }

        if (display && display.material && display.material.emissiveIntensity !== undefined) {
            // Pulse the display intensity to simulate varying SPL readings
            display.material.emissiveIntensity = 0.5 + Math.abs(Math.sin(time * speed * 5)) * 0.5;
        }

        if (grid) {
            // Slight rotation of the protection grid for a dynamic 3D effect
            grid.rotation.y = time * speed * 0.2;
        }
    };

    return { group, parts, description, quizQuestions, animate };
}

// Auto-generated missing stub
export function createSoundLevelMeterMicrophone() {
    const group = new THREE.Group();
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial({color: 0xff0000}));
    group.add(mesh);
    return group;
}
