import { plastic, aluminum, glass, copper, steel, darkSteel, rubber, chrome, tinted } from '../utils/materials.js';

export function createMachine(THREE) {
    const group = new THREE.Group();
    const parts = [];
    const meshes = {};

    // Custom glowing material for magnetic field
    const fieldMaterial = new THREE.MeshPhysicalMaterial({
        color: 0x00ffff,
        emissive: 0x00ffff,
        emissiveIntensity: 1.5,
        transparent: true,
        opacity: 0.0,
        transmission: 0.9,
        roughness: 0.1,
        side: THREE.DoubleSide
    });

    const neonWireMaterial = new THREE.MeshStandardMaterial({
        color: 0xffaa00,
        emissive: 0xffaa00,
        emissiveIntensity: 0.8
    });

    // 1. Casing (Figure-8)
    const casingGroup = new THREE.Group();
    const casingL = new THREE.Mesh(new THREE.TorusGeometry(1.5, 0.4, 32, 64), plastic);
    casingL.position.set(-1.4, 0, 0);
    casingL.rotation.x = Math.PI / 2;
    const casingR = new THREE.Mesh(new THREE.TorusGeometry(1.5, 0.4, 32, 64), plastic);
    casingR.position.set(1.4, 0, 0);
    casingR.rotation.x = Math.PI / 2;
    const bridge = new THREE.Mesh(new THREE.BoxGeometry(2.8, 0.8, 2.0), plastic);
    casingGroup.add(casingL, casingR, bridge);
    casingGroup.position.set(0, 0, 0);
    group.add(casingGroup);
    meshes.casing = casingGroup;

    parts.push({
        name: "Figure-8 Casing",
        description: "High-impact plastic housing that protects the internal copper windings and prevents electrical arcing to the patient.",
        material: "High-Dielectric Polymer",
        function: "Insulation and structural support",
        assemblyOrder: 5,
        connections: ["copperWindings", "handleArm"],
        failureEffect: "Risk of electric shock or dielectric breakdown.",
        cascadeFailures: ["Patient safety hazard", "Device short circuit"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: 2, z: 0 }
    });

    // 2. Copper Windings
    const windingsGroup = new THREE.Group();
    const windL = new THREE.Mesh(new THREE.TorusGeometry(1.2, 0.15, 16, 64), copper);
    windL.position.set(-1.4, 0, 0);
    windL.rotation.x = Math.PI / 2;
    const windR = new THREE.Mesh(new THREE.TorusGeometry(1.2, 0.15, 16, 64), copper);
    windR.position.set(1.4, 0, 0);
    windR.rotation.x = Math.PI / 2;
    windingsGroup.add(windL, windR);
    windingsGroup.position.set(0, 0, 0);
    group.add(windingsGroup);
    meshes.windings = windingsGroup;

    parts.push({
        name: "Copper Windings",
        description: "Densely packed copper coils configured in a figure-8 shape to create a highly focal magnetic field at the intersection.",
        material: "Oxygen-Free High Thermal Conductivity Copper",
        function: "Generates the rapid, high-intensity pulsed magnetic field.",
        assemblyOrder: 3,
        connections: ["coolingPipes", "capacitorBank"],
        failureEffect: "Loss of magnetic field output; overheating.",
        cascadeFailures: ["Cooling system overload", "Coil melting"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: 0, z: 0 }
    });

    // 3. Cooling System
    const coolingGroup = new THREE.Group();
    const pipe = new THREE.Mesh(new THREE.TorusGeometry(1.6, 0.05, 8, 64), chrome);
    pipe.position.set(-1.4, 0.2, 0);
    pipe.rotation.x = Math.PI / 2;
    const pipe2 = new THREE.Mesh(new THREE.TorusGeometry(1.6, 0.05, 8, 64), chrome);
    pipe2.position.set(1.4, 0.2, 0);
    pipe2.rotation.x = Math.PI / 2;
    coolingGroup.add(pipe, pipe2);
    coolingGroup.position.set(0, 0, 0);
    group.add(coolingGroup);
    meshes.cooling = coolingGroup;

    parts.push({
        name: "Active Liquid Cooling Tubes",
        description: "Circulates coolant to dissipate the massive heat generated by the rapid discharge of currents through the resistance of the coils.",
        material: "Chrome and Teflon",
        function: "Thermal management.",
        assemblyOrder: 4,
        connections: ["copperWindings", "coolantReservoir"],
        failureEffect: "Coil rapidly overheats and safety limits trip.",
        cascadeFailures: ["Insulation melting", "System shutdown"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: -2, z: 0 }
    });

    // 4. Handle & Positioning Arm
    const handleGroup = new THREE.Group();
    const arm = new THREE.Mesh(new THREE.CylinderGeometry(0.3, 0.3, 5, 32), aluminum);
    arm.position.set(0, 0, -3.5);
    arm.rotation.x = Math.PI / 2;
    const grip = new THREE.Mesh(new THREE.CylinderGeometry(0.4, 0.4, 2, 32), rubber);
    grip.position.set(0, 0, -4.5);
    grip.rotation.x = Math.PI / 2;
    
    // Add some neon wiring to the handle for sci-fi tech feel
    const handleWire = new THREE.Mesh(new THREE.TorusGeometry(0.32, 0.02, 8, 64), neonWireMaterial);
    handleWire.position.set(0, 0, -2.5);
    handleWire.rotation.x = Math.PI / 2;
    const handleWire2 = handleWire.clone();
    handleWire2.position.set(0, 0, -3.0);
    const handleWire3 = handleWire.clone();
    handleWire3.position.set(0, 0, -3.5);

    handleGroup.add(arm, grip, handleWire, handleWire2, handleWire3);
    group.add(handleGroup);
    meshes.handle = handleGroup;

    parts.push({
        name: "Positioning Arm & Handle",
        description: "Ergonomic, low-vibration handle allowing the operator to position the coil precisely over the target cortical region.",
        material: "Anodized Aluminum & Rubber",
        function: "Precise spatial navigation and operator control.",
        assemblyOrder: 2,
        connections: ["casing"],
        failureEffect: "Loss of positional accuracy.",
        cascadeFailures: ["Incorrect brain region stimulated"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: 0, z: -3 }
    });

    // 5. Magnetic Field Visualizer (Neon)
    const fieldGroup = new THREE.Group();
    const fieldShape = new THREE.Mesh(new THREE.SphereGeometry(1.5, 32, 32), fieldMaterial);
    fieldShape.position.set(0, -1.5, 0);
    fieldShape.scale.set(1, 1.5, 1);
    fieldGroup.add(fieldShape);
    group.add(fieldGroup);
    meshes.field = fieldGroup;

    parts.push({
        name: "Magnetic Field (Visualization)",
        description: "A pulsed, time-varying magnetic field (up to 2-3 Tesla) that penetrates the skull to induce an electric current in neural tissue.",
        material: "Electromagnetism",
        function: "Neuromodulation",
        assemblyOrder: 6,
        connections: ["copperWindings", "cortex"],
        failureEffect: "No therapeutic or diagnostic effect.",
        cascadeFailures: [],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: -4, z: 0 }
    });

    // 6. Pulse Capacitor Bank / Interface (Back unit)
    const controlUnit = new THREE.Group();
    const box = new THREE.Mesh(new THREE.BoxGeometry(2, 1, 3), darkSteel);
    box.position.set(0, 0, -7);
    const screen = new THREE.Mesh(new THREE.PlaneGeometry(1.8, 2.8), tinted);
    screen.position.set(0, 0.51, -7);
    screen.rotation.x = -Math.PI / 2;
    controlUnit.add(box, screen);
    group.add(controlUnit);
    meshes.controlUnit = controlUnit;

    parts.push({
        name: "High-Voltage Thyristor & Capacitor Bank",
        description: "Stores and rapidly discharges massive amounts of energy (kiloamperes) to create the high-frequency magnetic pulses.",
        material: "Dark Steel & Glass",
        function: "Pulse generation",
        assemblyOrder: 1,
        connections: ["copperWindings", "powerMains"],
        failureEffect: "No pulse generation; catastrophic component explosion.",
        cascadeFailures: ["Main fuse blown", "Complete system brick"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: 0, z: -8 }
    });

    const description = "Transcranial Magnetic Stimulation (TMS) is a non-invasive procedure that uses magnetic fields to stimulate nerve cells in the brain. The figure-8 coil generates a highly focal magnetic field that induces a localized electric current in the cortex, frequently used for depression treatment and cortical mapping.";

    const quizQuestions = [
        {
            question: "Why is the figure-8 (butterfly) coil shape preferred over a simple circular coil in precision TMS?",
            options: [
                "It requires less power to operate.",
                "It produces a more focal and concentrated magnetic field at the intersection.",
                "It reduces the heat generated by the device.",
                "It is lighter and easier to hold."
            ],
            correct: 1,
            explanation: "The figure-8 coil concentrates the magnetic field directly below the center point where the two loops meet, allowing for much more targeted stimulation of specific cortical regions compared to a circular coil.",
            difficulty: "Medium"
        },
        {
            question: "What physical principle allows the TMS magnetic field to stimulate neurons?",
            options: [
                "Faraday's law of electromagnetic induction",
                "The piezoelectric effect",
                "Quantum entanglement",
                "Thermodynamic equilibrium"
            ],
            correct: 0,
            explanation: "TMS relies on Faraday's law of induction. A rapidly changing magnetic field penetrates the skull and induces an electric current in the underlying conductive neural tissue, depolarizing neurons.",
            difficulty: "Hard"
        },
        {
            question: "Which component is most critical for preventing the TMS coil from overheating during high-frequency repetitive TMS (rTMS)?",
            options: [
                "The high-voltage capacitor",
                "The active liquid cooling system",
                "The aluminum positioning arm",
                "The glass control interface"
            ],
            correct: 1,
            explanation: "Pushing thousands of amps through copper resistance generates massive heat. An active liquid cooling system is required to keep the coil at safe temperatures during rapid, repetitive pulsing.",
            difficulty: "Easy"
        }
    ];

    const animate = (time, speed, activeMeshes = meshes) => {
        // Pulsing magnetic field effect
        if (activeMeshes.field) {
            const pulseRate = time * speed * 5;
            const intensity = Math.max(0, Math.sin(pulseRate) * 1.5 - 0.5); // Sharp pulses
            
            const fieldMesh = activeMeshes.field.children[0];
            if (fieldMesh && fieldMesh.material) {
                fieldMesh.material.opacity = intensity * 0.4;
                fieldMesh.scale.setScalar(1 + intensity * 0.1);
            }
        }
        
        // Slight vibration of the coil during pulse
        if (activeMeshes.casing && activeMeshes.windings && activeMeshes.cooling) {
            const pulseRate = time * speed * 5;
            const isPulsing = Math.sin(pulseRate) > 0.8;
            const jitter = isPulsing ? (Math.random() - 0.5) * 0.02 : 0;
            
            activeMeshes.casing.position.y = jitter;
            activeMeshes.windings.position.y = jitter;
            activeMeshes.cooling.position.y = jitter;
        }

        // Pulse the neon wires
        if (activeMeshes.handle) {
            const wires = [
                activeMeshes.handle.children[2],
                activeMeshes.handle.children[3],
                activeMeshes.handle.children[4]
            ];
            wires.forEach((wire, i) => {
                if (wire && wire.material) {
                    const wave = Math.sin(time * speed * 10 - i) * 0.5 + 0.5;
                    wire.material.emissiveIntensity = wave * 1.5;
                }
            });
        }
    };

    return { group, parts, description, quizQuestions, animate, meshes };
}

// Auto-generated missing stub
export function createTMS() {
    const group = new THREE.Group();
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial({color: 0xff0000}));
    group.add(mesh);
    return group;
}
