import { plastic, aluminum, glass, copper, steel, darkSteel, rubber, chrome, tinted } from '../utils/materials.js';

export function createMachine(THREE) {
    const group = new THREE.Group();
    const parts = [];
    
    // Custom High-Tech Glowing / Neon Materials
    const neonBlue = new THREE.MeshPhysicalMaterial({ color: 0x00f0ff, emissive: 0x00aaff, emissiveIntensity: 2, transparent: true, opacity: 0.9, roughness: 0.1, metalness: 0.8 });
    const neonGreen = new THREE.MeshPhysicalMaterial({ color: 0x00ff00, emissive: 0x00aa00, emissiveIntensity: 1.5, roughness: 0.2, metalness: 0.5 });
    const dataStreamMat = new THREE.MeshPhysicalMaterial({ color: 0xffffff, emissive: 0x00ffff, emissiveIntensity: 3, wireframe: true, transparent: true, opacity: 0.8 });

    // Main Chassis / Rack Cabinet
    const rackGeo = new THREE.BoxGeometry(4, 10, 4);
    const rackCabinet = new THREE.Mesh(rackGeo, darkSteel);
    rackCabinet.position.set(0, 5, 0);
    group.add(rackCabinet);
    parts.push({
        name: "Main Chassis / Rack",
        description: "Heavy-duty reinforced dark steel server rack housing the bioinformatics cluster.",
        material: "Dark Steel",
        function: "Provides structural integrity, electromagnetic shielding, and grounding.",
        assemblyOrder: 1,
        connections: ["All modules"],
        failureEffect: "Physical instability.",
        cascadeFailures: ["Vibration damage to blades", "Cooling leaks"],
        originalPosition: { x: 0, y: 5, z: 0 },
        explodedPosition: { x: 0, y: 15, z: 0 },
        mesh: rackCabinet
    });

    // Petabyte DNA Storage Array
    const storageGeo = new THREE.BoxGeometry(3.6, 2, 3.6);
    const storageArray = new THREE.Mesh(storageGeo, chrome);
    storageArray.position.set(0, 2, 0);
    group.add(storageArray);
    parts.push({
        name: "Petabyte DNA Storage Array",
        description: "High-speed NVMe storage holding raw genomic sequences and historical bioinformatics data.",
        material: "Chrome",
        function: "Stores massive biological datasets for rapid retrieval and processing.",
        assemblyOrder: 2,
        connections: ["Fiber Optic Backbone", "Main Chassis / Rack"],
        failureEffect: "Loss of sequencing data access.",
        cascadeFailures: ["Processing blades idle", "Pipeline halt"],
        originalPosition: { x: 0, y: 2, z: 0 },
        explodedPosition: { x: 0, y: 2, z: 10 },
        mesh: storageArray
    });

    // Genomic Processing Blades & Status LEDs
    for(let i=0; i<3; i++) {
        // Blade
        const bladeGeo = new THREE.BoxGeometry(3.4, 0.8, 3.8);
        const blade = new THREE.Mesh(bladeGeo, aluminum);
        blade.position.set(0, 4.5 + i*1.5, 0);
        group.add(blade);
        parts.push({
            name: `Genomic Processing Node ${i+1}`,
            description: `High-density AI compute node for genome alignment and protein folding simulations.`,
            material: "Aluminum",
            function: "Parallel processing of complex biological algorithms.",
            assemblyOrder: 3 + i,
            connections: ["Storage Array", "Quantum Liquid Cooling Unit"],
            failureEffect: "Reduced compute power.",
            cascadeFailures: ["Overload on remaining nodes", "Increased processing time"],
            originalPosition: { x: 0, y: 4.5 + i*1.5, z: 0 },
            explodedPosition: { x: -8 - (i*2), y: 4.5 + i*1.5, z: 0 },
            mesh: blade
        });
        
        // Neon LED Indicator
        const ledGeo = new THREE.BoxGeometry(3.6, 0.1, 0.1);
        const led = new THREE.Mesh(ledGeo, neonBlue);
        led.position.set(0, 4.5 + i*1.5, 1.95);
        group.add(led);
        parts.push({
            name: `Node ${i+1} Status LED`,
            description: "Activity indicator for the processing node.",
            material: "Neon Blue",
            function: "Provides visual feedback of node computational load.",
            assemblyOrder: 6 + i,
            connections: [`Genomic Processing Node ${i+1}`],
            failureEffect: "No visual status available.",
            cascadeFailures: [],
            originalPosition: { x: 0, y: 4.5 + i*1.5, z: 1.95 },
            explodedPosition: { x: -8 - (i*2), y: 4.5 + i*1.5, z: 5 },
            mesh: led
        });
    }

    // Quantum Liquid Cooling Unit
    const coolingGeo = new THREE.CylinderGeometry(1.5, 1.5, 1.5, 32);
    const coolingUnit = new THREE.Mesh(coolingGeo, copper);
    coolingUnit.rotation.x = Math.PI / 2;
    coolingUnit.position.set(0, 9, 0);
    group.add(coolingUnit);
    parts.push({
        name: "Quantum Liquid Cooling Unit",
        description: "Advanced copper-based liquid cooling manifold employing quantum phase-change materials.",
        material: "Copper",
        function: "Dissipates extreme heat generated by dense genomic processors.",
        assemblyOrder: 9,
        connections: ["All Genomic Processing Nodes"],
        failureEffect: "Thermal throttling of compute nodes.",
        cascadeFailures: ["Hardware meltdown", "Data corruption due to calculation errors"],
        originalPosition: { x: 0, y: 9, z: 0 },
        explodedPosition: { x: 0, y: 20, z: 0 },
        mesh: coolingUnit
    });

    // Fiber Optic Backbone
    const fiberGeo = new THREE.CylinderGeometry(0.2, 0.2, 8, 16);
    const fiber = new THREE.Mesh(fiberGeo, dataStreamMat);
    fiber.position.set(-1.5, 5, -1.5);
    group.add(fiber);
    parts.push({
        name: "Fiber Optic Backbone",
        description: "Terabit-per-second glowing data bus.",
        material: "Data Stream",
        function: "Facilitates ultra high-speed communication between storage and compute units.",
        assemblyOrder: 10,
        connections: ["Petabyte DNA Storage Array", "All Genomic Processing Nodes"],
        failureEffect: "Total cluster disconnect.",
        cascadeFailures: ["Computation halt", "Network timeout"],
        originalPosition: { x: -1.5, y: 5, z: -1.5 },
        explodedPosition: { x: -5, y: 5, z: -5 },
        mesh: fiber
    });

    // Holographic Status Interface
    const holoGeo = new THREE.PlaneGeometry(5, 3);
    const holoMat = new THREE.MeshPhysicalMaterial({ color: 0x00ffcc, emissive: 0x00ccaa, emissiveIntensity: 1, transparent: true, opacity: 0.6, side: THREE.DoubleSide });
    const holoDisp = new THREE.Mesh(holoGeo, holoMat);
    holoDisp.position.set(0, 12, 0);
    group.add(holoDisp);
    parts.push({
        name: "Holographic Status Interface",
        description: "Floating projected display showing real-time cluster health, DNA alignments, and sequencing progress.",
        material: "Holographic Glass",
        function: "Serves as the primary user interface and monitoring terminal.",
        assemblyOrder: 11,
        connections: ["Main Chassis / Rack"],
        failureEffect: "Loss of direct cluster monitoring.",
        cascadeFailures: ["Delayed response to system faults"],
        originalPosition: { x: 0, y: 12, z: 0 },
        explodedPosition: { x: 0, y: 12, z: 5 },
        mesh: holoDisp
    });

    const description = "The Bioinformatics Genomics Server Cluster is a state-of-the-art supercomputing array dedicated to decoding complex DNA, RNA, and protein structures. Equipped with Petabyte storage arrays, quantum liquid cooling, and parallel genomic processing nodes, it simulates biological processes at an unprecedented scale.";

    const quizQuestions = [
        {
            question: "What is the primary function of the Genomic Processing Nodes in this cluster?",
            options: [
                "Long-term archiving of patient records",
                "Parallel processing of complex biological algorithms like genome alignment",
                "Cooling the entire server system",
                "Generating holographic displays"
            ],
            correct: 1,
            explanation: "The compute nodes are highly parallelized specialized hardware dedicated to computationally expensive biological data processing, such as genome alignment and protein folding.",
            difficulty: "Medium"
        },
        {
            question: "Why is the Quantum Liquid Cooling Unit critical for the cluster's operation?",
            options: [
                "It powers the fiber optic backbone",
                "It encrypts the sensitive genetic data",
                "It prevents thermal throttling and potential hardware meltdown",
                "It acts as a backup power supply during outages"
            ],
            correct: 2,
            explanation: "Genomic computations run at 100% load for extended periods, generating extreme heat. The cooling unit dissipates this heat to prevent thermal throttling and hardware damage.",
            difficulty: "Easy"
        },
        {
            question: "What is the immediate consequence of a Fiber Optic Backbone failure?",
            options: [
                "The cooling system overheats",
                "Total cluster disconnect and computation halt due to data starvation",
                "The storage array deletes all data as a security measure",
                "The holographic interface changes color to red"
            ],
            correct: 1,
            explanation: "The backbone provides essential high-speed communication between the data storage and compute nodes. Its failure completely stops data flow, halting all genomic computations.",
            difficulty: "Hard"
        }
    ];

    function animate(time, speed, meshes) {
        // Animate the Fiber Optic Backbone data flow effect
        const fiber = parts.find(p => p.name === "Fiber Optic Backbone")?.mesh;
        if (fiber) {
            fiber.material.emissiveIntensity = 2 + Math.sin(time * speed * 15) * 1.5;
            fiber.rotation.y = time * speed * 0.5;
        }

        // Rotate the cooling unit fans / internals
        const cooling = parts.find(p => p.name === "Quantum Liquid Cooling Unit")?.mesh;
        if (cooling) {
            cooling.rotation.x = (Math.PI / 2) + Math.sin(time * speed * 5) * 0.1;
        }

        // Float and pulse the holographic display
        const holo = parts.find(p => p.name === "Holographic Status Interface")?.mesh;
        if (holo) {
            holo.position.y = 12 + Math.sin(time * speed * 2) * 0.2;
            holo.material.opacity = 0.5 + Math.sin(time * speed * 8) * 0.1;
        }

        // Animate blade LEDs for processing visualization
        for(let i=0; i<3; i++) {
            const led = parts.find(p => p.name === `Node ${i+1} Status LED`)?.mesh;
            if (led) {
                // Chaotic blinking effect simulating compute load
                led.material.emissiveIntensity = 1 + Math.random() * 2 * Math.abs(Math.sin(time * speed * (10 + i * 3)));
            }
        }
    }

    return { group, parts, description, quizQuestions, animate };
}
// Auto-generated missing stub
export function createServerCluster() {
    const group = new THREE.Group();
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial({color: 0xff0000}));
    group.add(mesh);
    return group;
}
