import { plastic, aluminum, glass, copper, steel, darkSteel, rubber, chrome, tinted } from '../utils/materials.js';

export function createMachine(THREE) {
    const group = new THREE.Group();
    const parts = [];

    // Custom Materials
    const ligninMaterial = new THREE.MeshPhysicalMaterial({
        color: 0x8B4513, // SaddleBrown
        metalness: 0.3,
        roughness: 0.7,
        clearcoat: 0.1,
        emissive: 0x3d200a,
        emissiveIntensity: 0.2
    });

    const waterMaterial = new THREE.MeshStandardMaterial({
        color: 0x00ffff,
        transparent: true,
        opacity: 0.8,
        emissive: 0x00ffff,
        emissiveIntensity: 0.8
    });

    const pitMaterial = new THREE.MeshPhysicalMaterial({
        color: 0x4aa34f,
        metalness: 0.1,
        roughness: 0.9,
        transparent: true,
        opacity: 0.5
    });
    
    // Meshes array for animation
    const meshes = {};

    // 1. Primary Vessel Element (The main tube)
    const vesselGeometry = new THREE.CylinderGeometry(2, 2, 20, 32, 1, true); // Open ended
    const vesselMesh = new THREE.Mesh(vesselGeometry, glass); // Using imported glass for outer layer visibility
    vesselMesh.position.set(0, 0, 0);
    group.add(vesselMesh);
    meshes.vessel = vesselMesh;

    parts.push({
        name: "Primary Vessel Element",
        description: "The main structural tube of the xylem, composed of dead cells called vessel elements arranged end-to-end.",
        material: "Lignified Cellulose / Transparent Glass representation",
        function: "Provides the main conduit for bulk water transport upwards through the plant.",
        assemblyOrder: 1,
        connections: ["Lignin Rings", "Perforation Plates", "Bordered Pits"],
        failureEffect: "Cavitation (air bubble formation) breaking the water column, stopping flow.",
        cascadeFailures: ["Water stress in leaves", "Stomatal closure", "Wilting"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: -10, y: 0, z: 0 }
    });

    // 2. Lignin Annular Rings (Reinforcement)
    meshes.rings = [];
    for (let i = -8; i <= 8; i += 2) {
        const ringGeo = new THREE.TorusGeometry(2.05, 0.2, 16, 32);
        const ringMesh = new THREE.Mesh(ringGeo, ligninMaterial);
        ringMesh.position.set(0, i, 0);
        ringMesh.rotation.x = Math.PI / 2;
        group.add(ringMesh);
        meshes.rings.push(ringMesh);
    }

    parts.push({
        name: "Lignin Annular Rings",
        description: "Rigid, spiral or ring-like thickenings of the secondary cell wall.",
        material: "Lignin Polymer",
        function: "Prevents the vessel from collapsing inward under the extreme negative pressure (tension) generated by transpiration.",
        assemblyOrder: 2,
        connections: ["Primary Vessel Element"],
        failureEffect: "Vessel collapse under negative pressure.",
        cascadeFailures: ["Complete blockage of water flow in the affected vessel"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 10, y: 0, z: 0 }
    });

    // 3. Perforation Plates (Ends of cells)
    const plateGeo = new THREE.CylinderGeometry(1.9, 1.9, 0.2, 32);
    // Make it look like a grate or grid
    const plateMaterial = new THREE.MeshStandardMaterial({
        color: 0x8B4513,
        wireframe: true,
        transparent: true,
        opacity: 0.6
    });
    
    const plateTop = new THREE.Mesh(plateGeo, plateMaterial);
    plateTop.position.set(0, 10, 0);
    group.add(plateTop);
    meshes.plateTop = plateTop;

    const plateBottom = new THREE.Mesh(plateGeo, plateMaterial);
    plateBottom.position.set(0, -10, 0);
    group.add(plateBottom);
    meshes.plateBottom = plateBottom;

    parts.push({
        name: "Perforation Plates",
        description: "End walls of the vessel elements with large openings or grating.",
        material: "Modified Cell Wall",
        function: "Allows unrestricted, low-resistance flow of water and dissolved minerals between consecutive vessel elements.",
        assemblyOrder: 3,
        connections: ["Primary Vessel Element"],
        failureEffect: "Increased hydraulic resistance.",
        cascadeFailures: ["Reduced water delivery rate to canopy"],
        originalPosition: { x: 0, y: 10, z: 0 },
        explodedPosition: { x: 0, y: 15, z: 0 }
    });

    // 4. Bordered Pits (Lateral transport)
    const pitGroup = new THREE.Group();
    meshes.pits = [];
    for(let i = 0; i < 8; i++) {
        const pitGeometry = new THREE.CylinderGeometry(0.5, 0.5, 0.5, 16);
        const pitMesh = new THREE.Mesh(pitGeometry, pitMaterial);
        
        const angle = (i / 8) * Math.PI * 2;
        const radius = 2;
        pitMesh.position.set(Math.cos(angle) * radius, 0, Math.sin(angle) * radius);
        pitMesh.rotation.z = Math.PI / 2;
        pitMesh.rotation.y = -angle;
        
        pitGroup.add(pitMesh);
        meshes.pits.push(pitMesh);
    }
    group.add(pitGroup);

    parts.push({
        name: "Bordered Pits",
        description: "Valves in the lateral walls of the vessels containing a torus and margo.",
        material: "Primary Cell Wall",
        function: "Allows lateral movement of water between adjacent vessels while preventing the spread of air embolisms (cavitation) by sealing off under pressure differentials.",
        assemblyOrder: 4,
        connections: ["Primary Vessel Element"],
        failureEffect: "Failure to seal allows air embolisms to spread to adjacent vessels.",
        cascadeFailures: ["Systemic cavitation", "Massive loss of hydraulic conductivity"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: 0, z: 10 }
    });

    // 5. Water Molecules (Transported fluid)
    const waterGroup = new THREE.Group();
    meshes.waterDrops = [];
    for(let i=0; i<30; i++) {
        const dropGeo = new THREE.SphereGeometry(0.3, 16, 16);
        const dropMesh = new THREE.Mesh(dropGeo, waterMaterial);
        
        // Random positions inside the tube
        const angle = Math.random() * Math.PI * 2;
        const r = Math.random() * 1.5;
        const y = (Math.random() * 20) - 10;
        
        dropMesh.position.set(Math.cos(angle)*r, y, Math.sin(angle)*r);
        // Store original y for animation
        dropMesh.userData.y = y;
        dropMesh.userData.speed = 0.05 + Math.random() * 0.05;
        
        waterGroup.add(dropMesh);
        meshes.waterDrops.push(dropMesh);
    }
    group.add(waterGroup);

    parts.push({
        name: "Cohesive Water Molecules",
        description: "H2O molecules exhibiting strong cohesive (to each other) and adhesive (to the vessel walls) forces.",
        material: "Water (H2O)",
        function: "Creates a continuous, unbroken chain of water pulled upward by the tension of transpiration from the leaves.",
        assemblyOrder: 5,
        connections: ["Primary Vessel Element"],
        failureEffect: "Loss of cohesion breaks the water column.",
        cascadeFailures: ["Transpiration pull fails to lift water"],
        originalPosition: { x: 0, y: 0, z: 0 },
        explodedPosition: { x: 0, y: 0, z: -10 }
    });


    const description = "A high-tech biomechanical visualization of a Xylem Vessel Element. Xylem acts as the structural plumbing of vascular plants, using the mechanical properties of lignin-reinforced tubes and the physical properties of water (cohesion and adhesion) to passively transport water and dissolved minerals from roots to shoots under extreme negative pressure.";

    const quizQuestions = [
        {
            question: "What is the primary function of the lignin annular rings in the xylem vessel?",
            options: [
                "To actively pump water upwards.",
                "To prevent the vessel from collapsing under the extreme negative pressure of transpiration.",
                "To store nutrients for the plant.",
                "To conduct photosynthesis in the stem."
            ],
            correct: 1,
            explanation: "Xylem vessels operate under immense negative pressure (tension) as water is pulled up by transpiration. Lignin rings provide essential structural reinforcement, preventing the tubes from collapsing inward.",
            difficulty: "Medium"
        },
        {
            question: "How do bordered pits help maintain the integrity of the plant's hydraulic system?",
            options: [
                "They generate ATP to power water movement.",
                "They actively filter out toxins from the soil.",
                "They act as safety valves that can seal off embolized (air-filled) vessels to prevent the spread of cavitation.",
                "They attract pollinators."
            ],
            correct: 2,
            explanation: "If an air bubble (embolism) forms in one vessel, the pressure difference causes the torus in the bordered pit to shift and seal against the pit border, preventing the air from spreading to adjacent functional vessels.",
            difficulty: "Hard"
        },
        {
            question: "What physical properties of water allow it to be pulled up the xylem without breaking?",
            options: [
                "Density and viscosity",
                "Compressibility and thermal conductivity",
                "Cohesion (hydrogen bonding between water molecules) and adhesion (bonding to the hydrophilic vessel walls)",
                "Evaporation and condensation"
            ],
            correct: 2,
            explanation: "The cohesion-tension theory relies on water molecules strongly bonding to each other (cohesion) and to the cellulose walls (adhesion), creating an unbroken, highly tensile liquid chain.",
            difficulty: "Medium"
        }
    ];

    function animate(time, speed, meshesObj) {
        const simSpeed = speed * 2;
        
        // Animate water molecules moving upwards
        if (meshesObj.waterDrops) {
            meshesObj.waterDrops.forEach((drop) => {
                drop.position.y += drop.userData.speed * simSpeed;
                
                // Reset to bottom if it reaches the top
                if (drop.position.y > 10) {
                    drop.position.y = -10;
                    
                    // Slightly randomize new horizontal position
                    const angle = Math.random() * Math.PI * 2;
                    const r = Math.random() * 1.5;
                    drop.position.x = Math.cos(angle) * r;
                    drop.position.z = Math.sin(angle) * r;
                }
            });
        }

        // Pulse the emissive intensity of the water for visual flair
        const pulse = (Math.sin(time * 0.005) * 0.5 + 0.5);
        if (meshesObj.waterDrops && meshesObj.waterDrops.length > 0) {
            meshesObj.waterDrops[0].material.emissiveIntensity = 0.5 + pulse * 0.5;
        }
    }

    return { group, parts, description, quizQuestions, animate, meshes };
}

// Auto-generated missing stub
export function createXylemVessel() {
    const group = new THREE.Group();
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial({color: 0xff0000}));
    group.add(mesh);
    return group;
}
