export function createFlagellum(THREE) {
    const parts = [];

    const createMat = (color) => new THREE.MeshStandardMaterial({
        color: color,
        roughness: 0.6,
        metalness: 0.1
    });

    const addPart = (name, description, mesh, spins) => {
        const group = new THREE.Group();
        group.add(mesh);
        parts.push({ name, description, mesh: group, spins });
    };

    // 1. Export Apparatus
    const exportApparatusGeo = new THREE.SphereGeometry(0.3, 16, 16);
    const exportApparatus = new THREE.Mesh(exportApparatusGeo, createMat(0xaa2222));
    exportApparatus.position.y = -2;
    addPart(
        'Export Apparatus',
        'Located at the base inside the cell, it exports flagellar proteins through the hollow core to assemble the flagellum.',
        exportApparatus,
        false
    );

    // 2. C-ring
    const cRingGeo = new THREE.TorusGeometry(0.8, 0.15, 16, 32);
    const cRing = new THREE.Mesh(cRingGeo, createMat(0x22aa22));
    cRing.rotation.x = Math.PI / 2;
    cRing.position.y = -1.5;
    addPart(
        'C-ring',
        'Cytoplasmic ring forming the rotor base, involved in torque generation and switching rotation direction.',
        cRing,
        true
    );

    // 3. Motor Switch Complex
    const switchComplex = new THREE.Group();
    const switchGeo = new THREE.BoxGeometry(0.2, 0.2, 0.2);
    const switchMat = createMat(0xdddd22);
    for(let i=0; i<8; i++) {
        const sw = new THREE.Mesh(switchGeo, switchMat);
        sw.position.set(Math.cos(i*Math.PI/4)*0.8, -1.6, Math.sin(i*Math.PI/4)*0.8);
        switchComplex.add(sw);
    }
    addPart(
        'Motor Switch Complex',
        'Interacts with chemotaxis proteins to change the direction of flagellar rotation.',
        switchComplex,
        true
    );

    // 4. MS-ring
    const msRingGeo = new THREE.TorusGeometry(0.6, 0.12, 16, 32);
    const msRing = new THREE.Mesh(msRingGeo, createMat(0x2222aa));
    msRing.rotation.x = Math.PI / 2;
    msRing.position.y = -1.0;
    addPart(
        'MS-ring',
        'Membrane/supramembrane ring embedded in the cytoplasmic membrane, acts as the mounting plate for the rotor.',
        msRing,
        true
    );

    // 5. Stator (MotA/MotB)
    const statorGroup = new THREE.Group();
    const statorGeo = new THREE.CylinderGeometry(0.1, 0.1, 0.8, 16);
    const statorMat = createMat(0xaa22aa);
    for(let i=0; i<10; i++) {
        const st = new THREE.Mesh(statorGeo, statorMat);
        st.position.set(Math.cos(i*Math.PI/5)*0.8, -1.0, Math.sin(i*Math.PI/5)*0.8);
        statorGroup.add(st);
    }
    addPart(
        'Stator (MotA/MotB)',
        'Stationary part anchored to the cell wall that conducts ions across the membrane to generate torque.',
        statorGroup,
        false
    );

    // 6. P-ring
    const pRingGeo = new THREE.TorusGeometry(0.5, 0.1, 16, 32);
    const pRing = new THREE.Mesh(pRingGeo, createMat(0xaaaa22));
    pRing.rotation.x = Math.PI / 2;
    pRing.position.y = -0.2;
    addPart(
        'P-ring',
        'Embedded in the peptidoglycan layer, it acts as a bushing for the rotating rod.',
        pRing,
        false
    );

    // 7. L-ring
    const lRingGeo = new THREE.TorusGeometry(0.5, 0.1, 16, 32);
    const lRing = new THREE.Mesh(lRingGeo, createMat(0x22aaaa));
    lRing.rotation.x = Math.PI / 2;
    lRing.position.y = 0.4;
    addPart(
        'L-ring',
        'Embedded in the outer lipopolysaccharide membrane, forming the outer bushing.',
        lRing,
        false
    );

    // 8. Rod
    const rodGeo = new THREE.CylinderGeometry(0.15, 0.15, 2.0, 16);
    const rod = new THREE.Mesh(rodGeo, createMat(0xcccccc));
    rod.position.y = -0.4;
    addPart(
        'Rod',
        'Transmits the torque generated by the motor to the hook and filament.',
        rod,
        true
    );

    // 9. Hook
    class HookCurve extends THREE.Curve {
        constructor() { super(); }
        getPoint(t, optionalTarget = new THREE.Vector3()) {
            const x = Math.sin(t * Math.PI / 2) * 0.5;
            const y = 0.6 + t * 0.8;
            const z = 0;
            return optionalTarget.set(x, y, z);
        }
    }
    const hookGeo = new THREE.TubeGeometry(new HookCurve(), 20, 0.18, 16, false);
    const hook = new THREE.Mesh(hookGeo, createMat(0xff8800));
    addPart(
        'Hook',
        'A flexible universal joint that transmits rotation from the motor to the filament.',
        hook,
        true
    );

    // 10. Filament
    class FilamentCurve extends THREE.Curve {
        constructor() { super(); }
        getPoint(t, optionalTarget = new THREE.Vector3()) {
            const radius = 0.5;
            const turns = 3;
            const length = 6.0;
            const angle = t * Math.PI * 2 * turns;
            const x = Math.cos(angle) * radius;
            const y = 1.4 + t * length;
            const z = Math.sin(angle) * radius;
            return optionalTarget.set(x, y, z);
        }
    }
    const filamentGeo = new THREE.TubeGeometry(new FilamentCurve(), 100, 0.12, 16, false);
    const filament = new THREE.Mesh(filamentGeo, createMat(0x0088ff));
    addPart(
        'Filament',
        'A long, helical propeller made of flagellin that drives the bacterium forward.',
        filament,
        true
    );

    const quiz = [
        {
            question: "Which part of the flagellum acts as a universal joint, transmitting torque to the filament?",
            options: ["L-ring", "Hook", "Export Apparatus", "Stator"],
            correctAnswer: 1,
            explanation: "The hook is a short, curved, flexible structure that connects the rod to the filament, acting as a universal joint."
        },
        {
            question: "What is the primary protein building block of the flagellar filament?",
            options: ["Actin", "Tubulin", "Flagellin", "Myosin"],
            correctAnswer: 2,
            explanation: "The flagellar filament is a hollow tube composed of thousands of copies of a single protein called flagellin."
        },
        {
            question: "What primarily powers the rotation of the bacterial flagellum in most species like E. coli?",
            options: ["ATP hydrolysis", "Proton Motive Force (PMF)", "GTP hydrolysis", "Light energy"],
            correctAnswer: 1,
            explanation: "Most bacterial flagellar motors are powered by the flow of protons (or sometimes sodium ions) across the cell membrane, known as the proton motive force."
        },
        {
            question: "In Gram-negative bacteria, which rings function as a bushing in the outer membrane and peptidoglycan layer?",
            options: ["MS-ring and C-ring", "L-ring and P-ring", "C-ring and Stator", "Export Apparatus and MS-ring"],
            correctAnswer: 1,
            explanation: "The L-ring (lipopolysaccharide) and P-ring (peptidoglycan) form a passive bushing that guides the rotating rod through the cell wall."
        },
        {
            question: "Which component is responsible for changing the direction of rotation (e.g., from counter-clockwise to clockwise)?",
            options: ["Motor Switch Complex", "L-ring", "Filament", "Hook"],
            correctAnswer: 0,
            explanation: "The Motor Switch Complex interacts with chemotaxis proteins to rapidly reverse the rotation of the motor, causing the bacterium to tumble."
        },
        {
            question: "When E. coli bacteria swim in a straight line (running), in which direction do their flagella rotate?",
            options: ["Clockwise", "Counter-clockwise", "Alternating every second", "They don't rotate, they whip back and forth"],
            correctAnswer: 1,
            explanation: "Counter-clockwise rotation bundles the flagella together, propelling the bacterium forward in a smooth 'run'. Clockwise rotation causes them to fly apart, resulting in a 'tumble'."
        }
    ];

    return {
        parts,
        animation: (time) => {
            parts.forEach(p => {
                if (p.spins) {
                    p.mesh.rotation.y = time * 3;
                }
            });
        },
        quiz
    };
}
