import { plastic, aluminum, glass, copper, steel, darkSteel, rubber, chrome, tinted } from '../utils/materials.js';

/**
 * ============================================================================
 * MICRO-WORMHOLE ROUTER (GOD TIER)
 * ============================================================================
 * WARNING: UNAUTHORIZED MODIFICATION OF TOPOLOGICAL ROUTING TABLES MAY RESULT
 * IN SEVERE SPACETIME DECOHERENCE, CAUSALITY VIOLATIONS, OR LOCALIZED FALSE 
 * VACUUM DECAY.
 * 
 * This module manages the creation, stabilization, and routing of millions of 
 * sub-atomic spatial tears for instantaneous intergalactic data transmission.
 * It utilizes an 11-dimensional Calabi-Yau manifold folding algorithm to 
 * bypass the speed of light, effectively creating a zero-latency internet.
 * 
 * DESIGN SPECIFICATIONS:
 * - Core: Suspended Exotic Matter / Negative Energy Condensate
 * - Shell: Degenerate Matter-infused Dark Steel
 * - Cooling: Superfluid Helium-4 / Hawking Radiation Dissipation Arrays
 * - Containment: Frame-dragging Superconducting Magnetic Rings
 * ============================================================================
 */

export function createMachine(THREE) {
    const group = new THREE.Group();
    const parts = [];
    const animationState = {
        time: 0,
        fibers: [],
        rings: [],
        nodes: [],
        pistons: [],
        spatialTears: null,
        wormholeCore: null,
        dataPackets: null
    };

    // ============================================================================
    // CUSTOM ADVANCED MATERIALS
    // ============================================================================
    const wormholeCoreMat = new THREE.MeshPhysicalMaterial({ 
        color: 0x050510, 
        emissive: 0x2200ff, 
        emissiveIntensity: 4, 
        roughness: 0.1, 
        transmission: 0.9, 
        thickness: 1.5,
        clearcoat: 1.0,
        clearcoatRoughness: 0.1
    });
    
    const spatialTearMat = new THREE.MeshStandardMaterial({ 
        color: 0x000000, 
        emissive: 0x8800ff, 
        emissiveIntensity: 10, 
        transparent: true, 
        opacity: 0.9, 
        blending: THREE.AdditiveBlending 
    });
    
    const fiberMat = new THREE.MeshStandardMaterial({ 
        color: 0x00ffff, 
        emissive: 0x00aaff, 
        emissiveIntensity: 2.0, 
        transparent: true, 
        opacity: 0.8 
    });
    
    const packetMat = new THREE.MeshStandardMaterial({ 
        color: 0xffffff, 
        emissive: 0xffffff, 
        emissiveIntensity: 6 
    });
    
    const superConductorMat = new THREE.MeshStandardMaterial({ 
        color: 0x111111, 
        roughness: 0.4, 
        metalness: 1.0, 
        emissive: 0x001122, 
        emissiveIntensity: 0.8 
    });
    
    const goldConnectorMat = new THREE.MeshStandardMaterial({ 
        color: 0xffd700, 
        roughness: 0.2, 
        metalness: 1.0 
    });
    
    const chassisMat = darkSteel;
    const coolingFinMat = aluminum;

    // ============================================================================
    // MAIN ROUTER CHASSIS BASE (Degenerate Matter Lathe)
    // ============================================================================
    const basePoints = [];
    // Procedural Lathe Geometry for extreme detail, iterating precisely
    for(let i = 0; i < 400; i++) {
        let y = (i / 400) * 30 - 20;
        let x = 18 + Math.sin(i * 0.15) * 3.5 - (y * y * 0.03) + Math.cos(i * 0.05) * 2.0;
        if (x < 2.0) x = 2.0;
        
        // Micro-ridges for quantum grip texturing
        if (i % 8 === 0) x += 0.8;
        if (i % 25 === 0) x -= 1.5;
        
        basePoints.push(new THREE.Vector2(x, y));
    }
    
    const baseGeo = new THREE.LatheGeometry(basePoints, 512); // Extreme poly count
    const baseMesh = new THREE.Mesh(baseGeo, chassisMat);
    group.add(baseMesh);
    
    parts.push({
        name: "Degenerate Matter Chassis Base",
        description: "The primary foundational structure, forged from hyper-dense degenerate matter to withstand the extreme gravitational shear forces generated by millions of localized spatial tears. Contains internal Heisenberg compensators.",
        material: "Dark Steel / Degenerate Matter",
        function: "Structural integrity and gravitational shielding.",
        assemblyOrder: 1,
        connections: ["Graviton Anchors", "Cooling Array", "Core Processor"],
        failureEffect: "Structural collapse leading to an uncontained micro-singularity.",
        cascadeFailures: ["Spacetime rupture", "Local system vaporization"],
        originalPosition: {x: 0, y: 0, z: 0},
        explodedPosition: {x: 0, y: -35, z: 0}
    });

    // ============================================================================
    // CENTRAL WORMHOLE CORE PROCESSOR
    // ============================================================================
    const coreGeo = new THREE.IcosahedronGeometry(8, 12); // Extremely high poly sphere
    const coreMesh = new THREE.Mesh(coreGeo, wormholeCoreMat);
    coreMesh.position.y = 20;
    group.add(coreMesh);
    animationState.wormholeCore = coreMesh;

    parts.push({
        name: "Central Wormhole Core Processor",
        description: "A suspended droplet of exotic matter forming the nexus of the router. It calculates the topological coordinates for million-node wormhole routing simultaneously across 11 dimensions using negative mass-energy algorithms.",
        material: "Exotic Matter / Quantum Glass",
        function: "Spatial tear computation and data packet routing.",
        assemblyOrder: 2,
        connections: ["Quantum Fibers", "Containment Field Generators"],
        failureEffect: "Routing tables corrupt, sending data packets into alternate dimensions.",
        cascadeFailures: ["Information paradox", "Timeline divergence", "Grandfather paradox induction"],
        originalPosition: {x: 0, y: 20, z: 0},
        explodedPosition: {x: 0, y: 45, z: 0}
    });

    // ============================================================================
    // MULTI-AXIAL CONTAINMENT RINGS (Frame-Dragging)
    // ============================================================================
    for (let i = 0; i < 15; i++) {
        let rad = 12 + i * 2.5;
        let tube = 0.25 + (0.15 * i);
        let ringGeo = new THREE.TorusGeometry(rad, tube, 128, 512); // High res
        let ringMesh = new THREE.Mesh(ringGeo, superConductorMat);
        ringMesh.position.y = 20;
        group.add(ringMesh);
        animationState.rings.push({ 
            mesh: ringMesh, 
            speedX: (Math.random() - 0.5) * 0.08, 
            speedY: (Math.random() - 0.5) * 0.08, 
            speedZ: (Math.random() - 0.5) * 0.08 
        });
    }

    parts.push({
        name: "Multi-Axial Containment Rings",
        description: "Superconducting magnetic arrays that prevent the central exotic matter core from collapsing into a black hole by constantly manipulating tensor fields via Lense-Thirring frame-dragging.",
        material: "Superconductor / Dark Steel",
        function: "Gravitational and topological containment.",
        assemblyOrder: 3,
        connections: ["Central Core Processor"],
        failureEffect: "Magnetic field destabilization.",
        cascadeFailures: ["Core collapse", "Singularity formation", "Ergosphere expansion"],
        originalPosition: {x: 0, y: 20, z: 0},
        explodedPosition: {x: 0, y: 20, z: 45}
    });

    // ============================================================================
    // QUANTUM FIBER-OPTICS (CatmullRom Branching Network)
    // ============================================================================
    for (let i = 0; i < 80; i++) {
        let points = [];
        for (let j = 0; j < 12; j++) {
            let r = 25 + (Math.random() * 6 - 3);
            let x = Math.cos(i * 0.35 + j) * r;
            let y = 0 + Math.sin(j * 1.5) * 20 + (Math.random() * 6 - 3);
            let z = Math.sin(i * 0.35 + j) * r;
            if (j === 0) {
                x = Math.cos(i * 0.35) * 8;
                y = -15;
                z = Math.sin(i * 0.35) * 8;
            } else if (j === 11) {
                x = Math.cos(i * 0.35) * 5;
                y = 20; // connect to core
                z = Math.sin(i * 0.35) * 5;
            }
            points.push(new THREE.Vector3(x, y, z));
        }
        let fiberCurve = new THREE.CatmullRomCurve3(points);
        let fiberGeo = new THREE.TubeGeometry(fiberCurve, 256, 0.2, 24, false);
        let fiberMesh = new THREE.Mesh(fiberGeo, fiberMat);
        group.add(fiberMesh);
        animationState.fibers.push({ mesh: fiberMesh, offset: Math.random() * 200 });
    }

    parts.push({
        name: "Quantum Fiber-Optic Trunks",
        description: "Hyper-threaded crystalline tubes that inject petabytes of traditional photon data into the wormhole core for inter-galactic translation. Capable of superluminal phase velocity.",
        material: "Quantum Glass / Copper",
        function: "Data injection and extraction.",
        assemblyOrder: 4,
        connections: ["Chassis Base", "Central Core Processor"],
        failureEffect: "Data packet loss and photon scattering.",
        cascadeFailures: ["Network latency spike", "Quantum decoherence"],
        originalPosition: {x: 0, y: 0, z: 0},
        explodedPosition: {x: 40, y: 0, z: -40}
    });

    // ============================================================================
    // THERMODYNAMIC DISSIPATION ARRAYS (Hawking Radiation Heat Sinks)
    // ============================================================================
    const heatSinkGroup = new THREE.Group();
    const heatSinkShape = new THREE.Shape();
    heatSinkShape.moveTo(0, 0);
    heatSinkShape.lineTo(6, 0);
    for(let f=0; f<50; f++) {
        heatSinkShape.lineTo(6 - (f%2)*1.0, f*0.7);
        heatSinkShape.lineTo(5.0 - (f%2)*1.0, f*0.7 + 0.35);
    }
    heatSinkShape.lineTo(0, 35);
    heatSinkShape.lineTo(0, 0);

    const extrudeSettings = { depth: 2.5, bevelEnabled: true, bevelSegments: 6, steps: 6, bevelSize: 0.2, bevelThickness: 0.2 };
    const heatSinkGeo = new THREE.ExtrudeGeometry(heatSinkShape, extrudeSettings);
    
    for(let i=0; i<32; i++) {
        const hsMesh = new THREE.Mesh(heatSinkGeo, coolingFinMat);
        const angle = (i / 32) * Math.PI * 2;
        hsMesh.position.set(Math.cos(angle) * 20, -18, Math.sin(angle) * 20);
        hsMesh.rotation.y = -angle + Math.PI/2;
        hsMesh.rotation.x = -Math.PI / 2;
        heatSinkGroup.add(hsMesh);
    }
    group.add(heatSinkGroup);

    parts.push({
        name: "Thermodynamic Dissipation Arrays",
        description: "Massive arrays of extruded aluminum-graphene fins designed to radiate away the immense Hawking radiation generated by the spatial tears. Uses a closed-loop superfluid helium-4 coolant system.",
        material: "Aluminum / Graphene",
        function: "Thermal regulation and Hawking radiation dissipation.",
        assemblyOrder: 5,
        connections: ["Chassis Base"],
        failureEffect: "Thermal runaway.",
        cascadeFailures: ["Core meltdown", "Plasma venting"],
        originalPosition: {x: 0, y: 0, z: 0},
        explodedPosition: {x: 0, y: -25, z: 50}
    });

    // ============================================================================
    // HARMONIC TUNING PISTONS (Hydraulic Alignment)
    // ============================================================================
    const pistonGeo = new THREE.CylinderGeometry(1.2, 1.2, 15, 64);
    const rodGeo = new THREE.CylinderGeometry(0.5, 0.5, 15, 64);
    const jointGeo = new THREE.SphereGeometry(1.5, 64, 64);
    
    for(let i=0; i<24; i++) {
        const pGroup = new THREE.Group();
        const pBase = new THREE.Mesh(pistonGeo, steel);
        const pRod = new THREE.Mesh(rodGeo, chrome);
        const pJoint = new THREE.Mesh(jointGeo, goldConnectorMat);
        pRod.position.y = 7.5;
        pJoint.position.y = 15;
        pGroup.add(pBase);
        pGroup.add(pRod);
        pGroup.add(pJoint);

        const angle = (i / 24) * Math.PI * 2;
        pGroup.position.set(Math.cos(angle) * 16, -5, Math.sin(angle) * 16);
        pGroup.rotation.x = Math.PI / 10; // Angled inward
        pGroup.rotation.y = -angle + Math.PI/2;
        
        group.add(pGroup);
        animationState.pistons.push({ rod: pRod, joint: pJoint, basePhase: i * 0.3 });
    }

    parts.push({
        name: "Harmonic Tuning Pistons",
        description: "High-pressure hydraulic actuators that constantly shift the physical alignment of the containment rings to adapt to topological space weather and gravitational waves.",
        material: "Steel / Chrome / Gold",
        function: "Dynamic spatial alignment.",
        assemblyOrder: 6,
        connections: ["Chassis Base", "Containment Rings"],
        failureEffect: "Misalignment of spatial tears.",
        cascadeFailures: ["Packet collision", "Sub-space fracture"],
        originalPosition: {x: 0, y: 0, z: 0},
        explodedPosition: {x: -45, y: 0, z: -45}
    });

    // ============================================================================
    // MICROSCOPIC SPATIAL TEARS (Millions simulated via InstancedMesh)
    // ============================================================================
    const tearCount = 200000;
    const tearGeo = new THREE.PlaneGeometry(0.12, 0.12);
    const tearInstanced = new THREE.InstancedMesh(tearGeo, spatialTearMat, tearCount);
    
    const dummy = new THREE.Object3D();
    const tearData = new Float32Array(tearCount * 5); 
    for(let i=0; i<tearCount; i++) {
        const u = Math.random();
        const v = Math.random();
        const theta = 2 * Math.PI * u;
        const phi = Math.acos(2 * v - 1);
        const r = 8.5 + Math.pow(Math.random(), 3) * 35;

        const x = r * Math.sin(phi) * Math.cos(theta);
        const y = 20 + r * Math.sin(phi) * Math.sin(theta);
        const z = r * Math.cos(phi);

        dummy.position.set(x, y, z);
        dummy.lookAt(new THREE.Vector3(0, 20, 0));
        dummy.updateMatrix();
        tearInstanced.setMatrixAt(i, dummy.matrix);

        tearData[i*5 + 0] = x;
        tearData[i*5 + 1] = y;
        tearData[i*5 + 2] = z;
        tearData[i*5 + 3] = Math.random() * Math.PI * 2; 
        tearData[i*5 + 4] = Math.random() * 0.25 + 0.05; 
    }
    tearInstanced.instanceMatrix.needsUpdate = true;
    group.add(tearInstanced);
    animationState.spatialTears = { mesh: tearInstanced, data: tearData, dummy: dummy };

    parts.push({
        name: "Micro-Wormhole Swarm",
        description: "Millions of localized, sub-atomic tears in the fabric of spacetime. Data packets are routed through these tears to achieve zero-latency galactic communication.",
        material: "Pure Energy / Spacetime",
        function: "Instantaneous data transmission across lightyears.",
        assemblyOrder: 7,
        connections: ["Central Core Processor"],
        failureEffect: "Event horizon expansion.",
        cascadeFailures: ["Router consumption", "Planetary destruction"],
        originalPosition: {x: 0, y: 20, z: 0},
        explodedPosition: {x: 0, y: 80, z: 0}
    });

    // ============================================================================
    // DATA PACKETS (Instanced Quantum Information)
    // ============================================================================
    const packetCount = 15000;
    const packetGeo = new THREE.BoxGeometry(0.15, 0.15, 0.6);
    const packetInstanced = new THREE.InstancedMesh(packetGeo, packetMat, packetCount);
    const packetData = [];
    for(let i=0; i<packetCount; i++) {
        packetData.push({
            fiberIndex: Math.floor(Math.random() * 80),
            progress: Math.random(),
            speed: Math.random() * 0.05 + 0.02
        });
        dummy.position.set(0,-1000,0);
        dummy.updateMatrix();
        packetInstanced.setMatrixAt(i, dummy.matrix);
    }
    packetInstanced.instanceMatrix.needsUpdate = true;
    group.add(packetInstanced);
    animationState.dataPackets = { mesh: packetInstanced, data: packetData, dummy: dummy };

    // ============================================================================
    // AUXILIARY MODULES (Error Correctors)
    // ============================================================================
    for (let p = 8; p <= 20; p++) {
        let extraGeo = new THREE.CylinderGeometry(2.0, 2.0, 5, 64);
        let extraMesh = new THREE.Mesh(extraGeo, darkSteel);
        extraMesh.position.set((p-14)*5.0, -12, 22);
        extraMesh.rotation.x = Math.PI/2;
        group.add(extraMesh);

        parts.push({
            name: `Auxiliary Module ${p}: Quantum Error Corrector Node ${String.fromCharCode(65+(p%26))}`,
            description: "Ensures that topological decoherence does not flip bits during wormhole transit. Uses an array of entangled qubits for parity checking to maintain data integrity over intergalactic distances.",
            material: "Dark Steel / Rubber",
            function: "Error correction and state observation.",
            assemblyOrder: p,
            connections: ["Chassis Base", "Data Bus"],
            failureEffect: "Data corruption.",
            cascadeFailures: ["Garbage data output", "Network congestion"],
            originalPosition: {x: (p-14)*5.0, y: -12, z: 22},
            explodedPosition: {x: (p-14)*8.0, y: -20, z: 35}
        });
    }

    // ============================================================================
    // DOCTORAL LEVEL PHYSICS / COMPUTING QUIZ
    // ============================================================================
    const quizQuestions = [
        {
            question: "In the context of the Central Wormhole Core Processor, if the exotic matter's negative energy density fluctuates below the critical threshold defined by the Casimir effect analog, what is the immediate topological consequence?",
            options: [
                "The wormhole throat pinches off, severing the connection.",
                "The wormhole expands into a macroscopic black hole.",
                "Data packets travel back in time due to closed timelike curves.",
                "The quantum fiber-optics undergo spontaneous crystallization."
            ],
            correctAnswer: 0,
            explanation: "Exotic matter with negative energy density is required to keep a traversable wormhole's throat open. If it drops below the threshold, the repulsive outward force fails to counteract gravity, causing the throat to collapse and pinch off the spatial tear."
        },
        {
            question: "When computing the routing metric across millions of spatial tears, the router utilizes a non-Euclidean topological tensor field. What happens to a data packet if its trajectory intersects a region with a non-zero Riemann curvature tensor but zero Ricci scalar?",
            options: [
                "The packet is destroyed by Hawking radiation.",
                "The packet undergoes extreme spaghettification but maintains informational integrity.",
                "The packet is subjected to tidal forces without local volume change, causing phase shifts.",
                "The packet's mass becomes imaginary, achieving tachyon state."
            ],
            correctAnswer: 2,
            explanation: "A zero Ricci scalar with a non-zero Riemann curvature tensor implies empty space with tidal forces (e.g., outside a mass). The packet's volume is locally conserved, but it stretches and squeezes, leading to quantum phase shifts without outright destruction."
        },
        {
            question: "The Harmonic Tuning Pistons modulate the containment rings. If the hydraulic frequency hits a resonant mode with the local vacuum zero-point energy fluctuations, what catastrophic cascade is initiated?",
            options: [
                "Vacuum decay, converting local spacetime to a lower energy state.",
                "The pistons solidify into degenerate matter.",
                "The containment rings induce a monopole magnetic field.",
                "The router emits a burst of localized Hawking radiation."
            ],
            correctAnswer: 0,
            explanation: "Resonance with vacuum zero-point fluctuations can provide the activation energy needed for a false vacuum to tunnel into a true vacuum, triggering a catastrophic bubble of vacuum decay that destroys all normal matter at the speed of light."
        },
        {
            question: "Why does the Micro-Wormhole Swarm require Instanced Spacetime Mapping rather than individual metric tensor calculations for each tear?",
            options: [
                "To reduce the localized gravity well footprint.",
                "To prevent the Pauli exclusion principle from blocking data packets.",
                "Because calculating N-body metric tensors scales at O(N!), exceeding the computational capacity of the exotic matter core.",
                "To allow packets to travel faster than light."
            ],
            correctAnswer: 2,
            explanation: "The topological interplay of millions of wormholes creates an immensely complex N-body gravity problem. Exact metric tensor calculation for each would exceed any computationally viable bounds (O(N!)), necessitating an instanced approximation matrix."
        },
        {
            question: "If a quantum fiber-optic trunk experiences decoherence while injecting a superpositioned data packet, what is the result on the receiving end of the wormhole network?",
            options: [
                "The packet arrives instantaneously but encrypted.",
                "The packet collapses into a definitive classical state, resulting in massive information loss.",
                "The packet reflects off the event horizon.",
                "The wormhole reverses its polarity."
            ],
            correctAnswer: 1,
            explanation: "Decoherence forces a quantum superposition to collapse into a single classical state. Since quantum data (qubits) relies on superpositions to carry exponentially more information, decoherence destroys the extra data, leaving only classical bits."
        }
    ];

    // ============================================================================
    // EXTREME ANIMATION LOGIC
    // ============================================================================
    function animate(time, speed, meshesObj) {
        const delta = speed * 0.01;
        animationState.time += delta;
        const t = animationState.time;

        // Animate the Exotic Matter Core
        if(animationState.wormholeCore) {
            animationState.wormholeCore.rotation.y = t * 1.1;
            animationState.wormholeCore.rotation.x = t * 0.7;
            animationState.wormholeCore.rotation.z = t * 0.4;
            // Complex multi-wave interference pattern for the core's glow
            const pulse = (Math.sin(t * 8) + Math.cos(t * 5.5) + Math.sin(t * 11) + 3) * 0.15; 
            animationState.wormholeCore.material.emissiveIntensity = 3 + pulse * 6;
            animationState.wormholeCore.scale.setScalar(1 + Math.sin(t * 18) * 0.05 + Math.cos(t * 9) * 0.03);
        }

        // Animate Containment Rings (Chaotic multi-axial rotation)
        animationState.rings.forEach(ring => {
            ring.mesh.rotation.x += ring.speedX * speed;
            ring.mesh.rotation.y += ring.speedY * speed;
            ring.mesh.rotation.z += ring.speedZ * speed;
        });

        // Animate Quantum Fiber-Optics (Chromatic phase shifting)
        animationState.fibers.forEach(fiber => {
            const hue = (t * 0.3 + fiber.offset) % 1;
            fiber.mesh.material.color.setHSL(hue, 1, 0.6);
            fiber.mesh.material.emissive.setHSL(hue, 1, 0.5);
        });

        // Animate Hydraulic Pistons (Harmonic adjustments)
        animationState.pistons.forEach(piston => {
            const offset = Math.sin(t * 5 + piston.basePhase) * 3.0;
            piston.rod.position.y = 7.5 + offset;
            piston.joint.position.y = 15 + offset;
        });

        // Animate Millions of Spatial Tears
        if(animationState.spatialTears) {
            const { mesh, data, dummy } = animationState.spatialTears;
            const count = data.length / 5;
            for(let i=0; i<count; i++) {
                const idx = i * 5;
                const x = data[idx + 0];
                const y = data[idx + 1];
                const z = data[idx + 2];
                let phase = data[idx + 3];
                const spd = data[idx + 4];

                phase += spd * speed;
                data[idx + 3] = phase; 

                // Dynamic scaling to simulate opening and closing
                const scale = 0.5 + 0.5 * Math.sin(phase * 22);
                
                // Micro-orbiting
                const ox = Math.sin(phase) * 1.0;
                const oy = Math.cos(phase * 1.5) * 1.0;
                const oz = Math.sin(phase * 2.1) * 1.0;

                dummy.position.set(x + ox, y + oy, z + oz);
                dummy.lookAt(0, 20, 0); 
                dummy.scale.set(scale, scale, scale);
                dummy.updateMatrix();
                
                mesh.setMatrixAt(i, dummy.matrix);
            }
            mesh.instanceMatrix.needsUpdate = true;
        }

        // Animate Data Packets traveling along Fibers
        if(animationState.dataPackets) {
            const { mesh, data, dummy } = animationState.dataPackets;
            for(let i=0; i<data.length; i++) {
                const packet = data[i];
                packet.progress += packet.speed * speed;
                if(packet.progress > 1) {
                    packet.progress = 0;
                    packet.fiberIndex = Math.floor(Math.random() * 80);
                }
                
                const j = packet.progress * 11;
                const r = 25;
                const i_idx = packet.fiberIndex;
                
                // Approximated path evaluation along the CatmullRom curve logic
                let px, py, pz;
                if(packet.progress < 0.1) {
                    const p = packet.progress / 0.1;
                    const startX = Math.cos(i_idx*0.35)*8;
                    const startY = -15;
                    const startZ = Math.sin(i_idx*0.35)*8;
                    const nextX = Math.cos(i_idx*0.35 + 1)*r;
                    const nextY = Math.sin(1.5)*20;
                    const nextZ = Math.sin(i_idx*0.35 + 1)*r;
                    px = startX * (1-p) + nextX * p;
                    py = startY * (1-p) + nextY * p;
                    pz = startZ * (1-p) + nextZ * p;
                } else if(packet.progress > 0.9) {
                    const p = (packet.progress - 0.9) / 0.1;
                    const prevX = Math.cos(i_idx*0.35 + 10)*r;
                    const prevY = Math.sin(10*1.5)*20;
                    const prevZ = Math.sin(i_idx*0.35 + 10)*r;
                    const endX = Math.cos(i_idx*0.35)*5;
                    const endY = 20;
                    const endZ = Math.sin(i_idx*0.35)*5;
                    px = prevX * (1-p) + endX * p;
                    py = prevY * (1-p) + endY * p;
                    pz = prevZ * (1-p) + endZ * p;
                } else {
                    px = Math.cos(i_idx*0.35 + j) * r;
                    py = Math.sin(j*1.5) * 20;
                    pz = Math.sin(i_idx*0.35 + j) * r;
                }

                dummy.position.set(px, py, pz);
                // Rotate packet to match direction (approximated)
                dummy.rotation.set(px, py, pz);
                dummy.updateMatrix();
                
                mesh.setMatrixAt(i, dummy.matrix);
            }
            mesh.instanceMatrix.needsUpdate = true;
        }
    }

    return { 
        group, 
        parts, 
        description: "A God-Tier Micro-Wormhole Router capable of establishing millions of stable, sub-atomic spacetime tears for instantaneous, zero-latency galactic internet. Warning: Prolonged observation may induce topological psychosis and causality paradoxes.", 
        quizQuestions, 
        animate 
    };
}
