import { plastic, aluminum, glass, copper, steel, darkSteel, rubber, chrome, tinted } from '../utils/materials.js';

export function createMachine(THREE) {
    const group = new THREE.Group();
    const parts = [];
    const interactiveMeshes = {};

    // --- Custom Emissive & High-Tech Materials ---
    const plasmaBlueMaterial = new THREE.MeshStandardMaterial({
        color: 0x00ffff,
        emissive: 0x00ffff,
        emissiveIntensity: 3.5,
        transparent: true,
        opacity: 0.85,
        roughness: 0.1,
        metalness: 0.8
    });

    const antimatterRedMaterial = new THREE.MeshStandardMaterial({
        color: 0xff0044,
        emissive: 0xff0022,
        emissiveIntensity: 2.0,
        transparent: true,
        opacity: 0.9
    });

    const dilithiumMaterial = new THREE.MeshPhysicalMaterial({
        color: 0xffffff,
        emissive: 0xffaaff,
        emissiveIntensity: 1.0,
        transmission: 0.9,
        opacity: 1.0,
        metalness: 0.1,
        roughness: 0.05,
        ior: 2.5,
        thickness: 2.0
    });

    const containmentFieldMaterial = new THREE.MeshPhysicalMaterial({
        color: 0x0055ff,
        emissive: 0x0022ff,
        emissiveIntensity: 0.5,
        transparent: true,
        opacity: 0.3,
        transmission: 0.6,
        roughness: 0.0,
        metalness: 0.2,
        side: THREE.DoubleSide
    });

    const pulseGoldMaterial = new THREE.MeshStandardMaterial({
        color: 0xffaa00,
        emissive: 0xcc7700,
        emissiveIntensity: 1.5,
        metalness: 1.0,
        roughness: 0.2
    });

    // Helper: Register Part
    const addPart = (name, description, material, functionDesc, assemblyOrder, originalPos, geometry, meshGroup, connections, failureEffect, cascadeFailures, isInteractive = true) => {
        const mesh = new THREE.Mesh(geometry, material);
        mesh.position.copy(originalPos);
        mesh.castShadow = true;
        mesh.receiveShadow = true;
        
        mesh.userData = { name, description, isInteractive };
        if (meshGroup) meshGroup.add(mesh);
        else group.add(mesh);
        
        const explodedPos = new THREE.Vector3(
            originalPos.x * 2.5 + (Math.random() * 10 - 5),
            originalPos.y * 1.5 + (Math.random() * 10 - 5),
            originalPos.z * 2.5 + (Math.random() * 10 - 5)
        );

        const partData = {
            name,
            description,
            material: material ? material.type : 'Mixed',
            function: functionDesc,
            assemblyOrder,
            connections,
            failureEffect,
            cascadeFailures,
            originalPosition: { x: originalPos.x, y: originalPos.y, z: originalPos.z },
            explodedPosition: { x: explodedPos.x, y: explodedPos.y, z: explodedPos.z }
        };

        parts.push(partData);
        interactiveMeshes[name] = mesh;
        return mesh;
    };

    // --- Core Architecture Geometries ---
    
    // 1. Central Containment Chamber (Towering Glass/Field cylinder)
    const chamberRadius = 4;
    const chamberHeight = 40;
    const chamberGeo = new THREE.CylinderGeometry(chamberRadius, chamberRadius, chamberHeight, 64, 1, true);
    addPart(
        "Reaction Chamber Outer Casing",
        "Primary containment structure fabricated from transparent aluminum to withstand extreme thermal stresses.",
        glass,
        "Houses the primary antimatter reaction and maintains vacuum integrity.",
        5,
        new THREE.Vector3(0, 0, 0),
        chamberGeo,
        group,
        ["Magnetic Constriction Rings", "Dilithium Matrix"],
        "Loss of atmospheric vacuum inside the chamber; micro-fractures in transparent aluminum.",
        ["Containment breach", "Catastrophic warp core explosion"]
    );

    // 2. Inner Plasma Column (Glowing Blue)
    const plasmaGeo = new THREE.CylinderGeometry(chamberRadius * 0.7, chamberRadius * 0.7, chamberHeight * 0.95, 32, 32);
    interactiveMeshes.plasmaColumn = addPart(
        "Plasma Reaction Stream",
        "The highly energetic electro-plasma stream generated by matter/antimatter annihilation.",
        plasmaBlueMaterial,
        "Provides raw power to the warp nacelles via EPS conduits.",
        6,
        new THREE.Vector3(0, 0, 0),
        plasmaGeo,
        group,
        ["EPS Power Tap Assembly", "Dilithium Matrix"],
        "Plasma stream destabilization; erratic power output.",
        ["Warp field collapse", "Nacelle plasma blowout"]
    );

    // 3. Magnetic Constriction Rings (Stacked Torus array with complex details)
    const ringCount = 12;
    const ringGroup = new THREE.Group();
    group.add(ringGroup);
    
    for (let i = 0; i < ringCount; i++) {
        const ringY = (i - (ringCount-1)/2) * (chamberHeight / ringCount);
        // Primary Ring
        const ringGeo = new THREE.TorusGeometry(chamberRadius * 1.3, 0.6, 32, 64);
        const ringMesh = addPart(
            `Magnetic Constriction Ring ${i+1}`,
            `Electromagnetic torus module ${i+1} focusing the antimatter stream.`,
            darkSteel,
            "Compresses the plasma stream to prevent contact with the outer casing.",
            10 + i,
            new THREE.Vector3(0, ringY, 0),
            ringGeo,
            ringGroup,
            ["Reaction Chamber Outer Casing", "Isomagnetic Regulators"],
            `Loss of localized magnetic constriction at level ${i+1}.`,
            ["Plasma bloom", "Containment wall scorch", "Chain reaction failure of adjacent rings"]
        );

        // Add detailed nodes around the ring
        const nodeGeo = new THREE.CylinderGeometry(0.8, 0.8, 1.5, 16);
        for(let j = 0; j < 8; j++) {
            const angle = (j / 8) * Math.PI * 2;
            const nodeMesh = new THREE.Mesh(nodeGeo, chrome);
            nodeMesh.position.set(Math.cos(angle) * chamberRadius * 1.3, 0, Math.sin(angle) * chamberRadius * 1.3);
            nodeMesh.rotation.x = Math.PI / 2;
            nodeMesh.rotation.z = angle;
            ringMesh.add(nodeMesh);
            
            // Glowing inset
            const glowGeo = new THREE.SphereGeometry(0.4, 16, 16);
            const glowMesh = new THREE.Mesh(glowGeo, pulseGoldMaterial);
            glowMesh.position.set(0, 0.8, 0);
            nodeMesh.add(glowMesh);
            
            // Add a reference for animation
            if (!interactiveMeshes.pulseNodes) interactiveMeshes.pulseNodes = [];
            interactiveMeshes.pulseNodes.push(glowMesh);
        }
    }

    // 4. Upper Matter Injector Assembly
    const injectorPoints = [
        new THREE.Vector2(1, 0),
        new THREE.Vector2(3, 2),
        new THREE.Vector2(3, 4),
        new THREE.Vector2(5, 5),
        new THREE.Vector2(5, 8),
        new THREE.Vector2(2, 10),
        new THREE.Vector2(2, 12),
        new THREE.Vector2(0, 12)
    ];
    const injectorGeo = new THREE.LatheGeometry(injectorPoints, 64);
    addPart(
        "Upper Matter Injector Assembly",
        "Precisely calibrated deuterium injection manifold.",
        chrome,
        "Injects normal matter (deuterium) into the reaction chamber at relativistic speeds.",
        1,
        new THREE.Vector3(0, chamberHeight/2, 0),
        injectorGeo,
        group,
        ["Deuterium Flow Valves", "Reaction Chamber Outer Casing"],
        "Deuterium flow restriction; engine misfire.",
        ["Asymmetric reaction", "Warp core shutdown"]
    );

    // 5. Lower Antimatter Injector Assembly
    const amInjectorGeo = new THREE.LatheGeometry(injectorPoints, 64);
    const amInjectorPart = addPart(
        "Lower Antimatter Injector",
        "Magnetic-levitation anti-hydrogen injection array.",
        steel,
        "Injects antimatter upward to annihilate with matter at the exact core center.",
        2,
        new THREE.Vector3(0, -chamberHeight/2, 0),
        amInjectorGeo,
        group,
        ["Reaction Chamber Outer Casing", "Isomagnetic Regulators"],
        "Antimatter containment slip; premature annihilation.",
        ["Injector assembly destruction", "Core breach"]
    );
    amInjectorPart.rotation.x = Math.PI; // Flip it upside down

    // 6. Dilithium Crystal Matrix Housing (Center of the core)
    const housingPoints = [
        new THREE.Vector2(2, -3),
        new THREE.Vector2(4, -1),
        new THREE.Vector2(4, 1),
        new THREE.Vector2(2, 3),
        new THREE.Vector2(0, 3)
    ];
    const housingGeo = new THREE.LatheGeometry(housingPoints, 8);
    const matrixHousing = addPart(
        "Dilithium Crystal Matrix Housing",
        "Articulated multi-axis frame holding the dilithium crystals.",
        darkSteel,
        "Channels and regulates the matter/antimatter reaction into a usable plasma stream.",
        3,
        new THREE.Vector3(0, 0, 0),
        housingGeo,
        group,
        ["Upper Matter Injector Assembly", "Lower Antimatter Injector"],
        "Matrix misalignment; reaction efficiency drop.",
        ["Crystal decrystalization", "Uncontrolled annihilation"]
    );
    
    // 7. The Dilithium Crystal itself
    const crystalGeo = new THREE.IcosahedronGeometry(1.5, 1);
    const crystalMesh = addPart(
        "Dilithium Crystal",
        "High-grade, fifth-dimensionally phased dilithium composite.",
        dilithiumMaterial,
        "The only substance known to withstand matter/antimatter annihilation, acting as a focusing medium.",
        4,
        new THREE.Vector3(0, 0, 0),
        crystalGeo,
        matrixHousing,
        ["Dilithium Crystal Matrix Housing"],
        "Crystal fracturing.",
        ["Complete reaction failure", "Massive core explosion"]
    );
    interactiveMeshes.crystal = crystalMesh;

    // 8. EPS Power Tap Assembly (Extracts energy)
    const tapGeo = new THREE.BoxGeometry(6, 4, 10);
    const tapMesh = addPart(
        "EPS Power Tap Assembly",
        "Massive Electro-Plasma System distribution hub.",
        copper,
        "Siphons generated plasma from the reaction chamber into the ship's power grid.",
        25,
        new THREE.Vector3(0, 10, chamberRadius + 3),
        tapGeo,
        group,
        ["Plasma Reaction Stream", "Plasma Conduit Port", "Plasma Conduit Starboard"],
        "Power grid surge.",
        ["Blown EPS relays ship-wide", "Consoles exploding on the bridge"]
    );

    // 9 & 10. Plasma Conduits (Tube Geometries routing power outward)
    class ConduitCurve extends THREE.Curve {
        constructor(startX, startY, startZ, endX, endY, endZ) {
            super();
            this.start = new THREE.Vector3(startX, startY, startZ);
            this.end = new THREE.Vector3(endX, endY, endZ);
            this.mid1 = new THREE.Vector3(startX * 1.5, startY, startZ * 1.5);
            this.mid2 = new THREE.Vector3(endX * 1.5, endY, endZ * 1.5);
        }
        getPoint(t, optionalTarget = new THREE.Vector3()) {
            const pt = new THREE.Vector3();
            pt.copy(this.start).lerp(this.mid1, t);
            const pt2 = new THREE.Vector3().copy(this.mid2).lerp(this.end, t);
            const mid = new THREE.Vector3().copy(this.mid1).lerp(this.mid2, t);
            
            const smooth1 = new THREE.Vector3().copy(pt).lerp(mid, t);
            const smooth2 = new THREE.Vector3().copy(mid).lerp(pt2, t);
            
            return optionalTarget.copy(smooth1).lerp(smooth2, t);
        }
    }

    const portCurve = new ConduitCurve(0, 10, chamberRadius + 8, -25, 20, 15);
    const portConduitGeo = new THREE.TubeGeometry(portCurve, 64, 1.5, 16, false);
    addPart(
        "Plasma Conduit (Port)",
        "Heavy-duty magnetic plasma transfer tube.",
        chrome,
        "Routes high-energy plasma to the port warp nacelle.",
        26,
        new THREE.Vector3(0, 0, 0), // Position is baked into the curve
        portConduitGeo,
        group,
        ["EPS Power Tap Assembly"],
        "Conduit rupture.",
        ["Plasma venting onto engineering decks", "Port nacelle shutdown"]
    );

    const starboardCurve = new ConduitCurve(0, 10, chamberRadius + 8, 25, 20, 15);
    const starboardConduitGeo = new THREE.TubeGeometry(starboardCurve, 64, 1.5, 16, false);
    addPart(
        "Plasma Conduit (Starboard)",
        "Heavy-duty magnetic plasma transfer tube.",
        chrome,
        "Routes high-energy plasma to the starboard warp nacelle.",
        27,
        new THREE.Vector3(0, 0, 0),
        starboardConduitGeo,
        group,
        ["EPS Power Tap Assembly"],
        "Conduit rupture.",
        ["Plasma venting", "Starboard nacelle shutdown"]
    );

    // 11. Coolant Subsystem Alpha
    const coolantGeo = new THREE.CylinderGeometry(1, 1, chamberHeight * 0.8, 16);
    addPart(
        "Coolant Subsystem Alpha",
        "Cryogenic fluid circulation pipeline.",
        aluminum,
        "Maintains safe operating temperatures for the outer casing.",
        30,
        new THREE.Vector3(-chamberRadius - 2, 0, -chamberRadius - 2),
        coolantGeo,
        group,
        ["Reaction Chamber Outer Casing"],
        "Coolant leak.",
        ["Overheating", "Auto-shutdown protocols engaged"]
    );

    // 12. Coolant Subsystem Beta
    addPart(
        "Coolant Subsystem Beta",
        "Redundant cryogenic fluid circulation pipeline.",
        aluminum,
        "Secondary thermal regulation.",
        31,
        new THREE.Vector3(chamberRadius + 2, 0, -chamberRadius - 2),
        coolantGeo,
        group,
        ["Reaction Chamber Outer Casing"],
        "Coolant leak.",
        ["Reliance on Alpha subsystem", "Thermal efficiency drop"]
    );

    // 13. Isomagnetic Regulators
    const isoRegGeo = new THREE.BoxGeometry(2, 6, 2);
    for(let i=0; i<4; i++) {
        const angle = (i/4) * Math.PI * 2;
        const rPos = new THREE.Vector3(Math.cos(angle) * (chamberRadius + 1), -10, Math.sin(angle) * (chamberRadius + 1));
        addPart(
            `Isomagnetic Regulator ${i+1}`,
            "Precision magnetic field tuning device.",
            plastic,
            "Fine-tunes the constriction rings to handle power fluctuations.",
            40 + i,
            rPos,
            isoRegGeo,
            group,
            ["Magnetic Constriction Ring 1", "Magnetic Constriction Ring 2"],
            "Magnetic field wobble.",
            ["Plasma instability"]
        );
    }

    // 14. Subspace Field Stabilizer
    const stabilizerGeo = new THREE.TorusGeometry(chamberRadius * 2, 1, 32, 100);
    const stabilizerMesh = addPart(
        "Subspace Field Stabilizer",
        "Large gyroscopic ring maintaining local subspace integrity.",
        steel,
        "Prevents the massive energy output from folding space inside the engineering bay.",
        50,
        new THREE.Vector3(0, -chamberHeight/2 + 2, 0),
        stabilizerGeo,
        group,
        ["Lower Antimatter Injector"],
        "Subspace micro-tears.",
        ["Spatial distortion inside the ship", "Structural shear"]
    );
    interactiveMeshes.stabilizerRing = stabilizerMesh;

    // 15. Warp Core Ejection Diagnostics Port
    const portEjectGeo = new THREE.CylinderGeometry(3, 3, 2, 32);
    addPart(
        "Warp Core Ejection Diagnostics Port",
        "Emergency explosive bolt interface.",
        antimatterRedMaterial,
        "Interface for the command to blast the core into space in case of imminent breach.",
        60,
        new THREE.Vector3(0, -chamberHeight/2 - 2, 0),
        portEjectGeo,
        group,
        ["Subspace Field Stabilizer", "Lower Antimatter Injector"],
        "Ejection system jam.",
        ["Inability to eject a breaching core", "Total ship destruction"]
    );

    // 16. Deuterium Flow Valves
    const valveGeo = new THREE.SphereGeometry(2, 32, 32);
    addPart(
        "Deuterium Flow Valves",
        "High-pressure mechanical valves for matter injection.",
        copper,
        "Regulates the exact milligram flow of deuterium into the upper injector.",
        61,
        new THREE.Vector3(0, chamberHeight/2 + 3, 0),
        valveGeo,
        group,
        ["Upper Matter Injector Assembly"],
        "Valve stuck open.",
        ["Matter over-saturation", "Reaction imbalance"]
    );

    // 17. Antimatter Containment Pod Array (Base)
    const podGeo = new THREE.CapsuleGeometry(2, 6, 16, 32);
    for(let i=0; i<3; i++) {
        const pAngle = (i/3) * Math.PI * 2;
        const podMesh = addPart(
            `Antimatter Storage Pod ${i+1}`,
            "Magnetically suspended anti-hydrogen storage.",
            darkSteel,
            "Stores antimatter safely before injection.",
            70 + i,
            new THREE.Vector3(Math.cos(pAngle) * 10, -chamberHeight/2 - 10, Math.sin(pAngle) * 10),
            podGeo,
            group,
            ["Lower Antimatter Injector"],
            "Magnetic suspension failure.",
            ["Pod annihilation", "Chain reaction destroying other pods and core"]
        );
        
        // Add glowing window to pod
        const windowGeo = new THREE.BoxGeometry(2.2, 4, 1);
        const windowMesh = new THREE.Mesh(windowGeo, antimatterRedMaterial);
        windowMesh.position.set(0, 0, 1.5);
        podMesh.add(windowMesh);
    }

    // --- Complex Animation Logic ---
    const animate = (time, speed, meshes) => {
        const t = time * speed;
        
        // 1. Plasma Column pulsating
        if (interactiveMeshes.plasmaColumn) {
            const pulse = (Math.sin(t * 5) * 0.5 + 0.5);
            interactiveMeshes.plasmaColumn.material.emissiveIntensity = 2.0 + pulse * 3.0;
            interactiveMeshes.plasmaColumn.scale.x = 1.0 + pulse * 0.05;
            interactiveMeshes.plasmaColumn.scale.z = 1.0 + pulse * 0.05;
            
            // Texture offset if it had one, but we use procedural scaling here
        }

        // 2. Crystal Floating and Rotating
        if (interactiveMeshes.crystal) {
            interactiveMeshes.crystal.rotation.y = t * 2.0;
            interactiveMeshes.crystal.rotation.x = t * 1.5;
            interactiveMeshes.crystal.position.y = Math.sin(t * 3) * 0.5;
            interactiveMeshes.crystal.material.emissiveIntensity = (Math.sin(t * 8) * 0.5 + 0.5) * 2.0;
        }

        // 3. Magnetic Constriction Rings Sequencing
        if (ringGroup) {
            ringGroup.children.forEach((ring, index) => {
                // Alternating rotation directions for the rings
                const dir = index % 2 === 0 ? 1 : -1;
                ring.rotation.y = t * dir * (1.0 + (index * 0.05));
                
                // Slight vertical pumping motion representing magnetic waves
                const wave = Math.sin(t * 4 + index * 0.5) * 0.2;
                // Keep base Y, just add wave. Base Y is calculated during init, so we need to store it or recalculate.
                // Re-calculate base Y:
                const ringY = (index - (ringCount-1)/2) * (chamberHeight / ringCount);
                ring.position.y = ringY + wave;
            });
        }

        // 4. Pulse Nodes on the Rings
        if (interactiveMeshes.pulseNodes) {
            interactiveMeshes.pulseNodes.forEach((node, i) => {
                node.material.emissiveIntensity = (Math.sin(t * 10 + i) * 0.5 + 0.5) * 4.0;
            });
        }

        // 5. Subspace Stabilizer Ring tumbling
        if (interactiveMeshes.stabilizerRing) {
            interactiveMeshes.stabilizerRing.rotation.x = Math.sin(t) * 0.2;
            interactiveMeshes.stabilizerRing.rotation.z = Math.cos(t) * 0.2;
            interactiveMeshes.stabilizerRing.rotation.y = t * -0.5;
        }
    };

    const description = "The Xenodynamics Mark VII Antimatter Warp Core is a massive, hyper-complex energy generation facility designed for faster-than-light propulsion. It uses perfectly synchronized magnetic constriction rings to align deuterium and antihydrogen streams, colliding them precisely within a fifth-dimensional dilithium matrix to generate tremendous electro-plasma energy.";

    const quizQuestions = [
        {
            question: "What is the primary function of the Magnetic Constriction Rings?",
            options: [
                "To cool the core casing",
                "To compress and focus the plasma stream",
                "To generate artificial gravity",
                "To inject deuterium"
            ],
            correctAnswer: 1,
            explanation: "The rings use immense electromagnetic fields to compress the matter and antimatter streams, keeping them away from the physical casing and focusing the reaction."
        },
        {
            question: "Why is the Dilithium Crystal Matrix essential?",
            options: [
                "It looks pretty and glows",
                "It is the only material that can regulate matter/antimatter annihilation",
                "It stores the antimatter",
                "It pumps cryogenic coolant"
            ],
            correctAnswer: 1,
            explanation: "Dilithium is uniquely capable of withstanding high-frequency annihilation reactions and acts as a porous focusing medium to generate safe, usable electro-plasma."
        },
        {
            question: "What happens if the Coolant Subsystems fail?",
            options: [
                "The core freezes over",
                "Thermal runaway leading to auto-shutdown or core breach",
                "The ship travels faster",
                "Nothing, they are purely cosmetic"
            ],
            correctAnswer: 1,
            explanation: "Without coolant, the massive thermal energy of the reaction would melt the transparent aluminum casing, leading to catastrophic containment failure."
        },
        {
            question: "Where is the antimatter injected from?",
            options: [
                "The Upper Matter Injector",
                "The EPS Power Taps",
                "The Lower Antimatter Injector",
                "The Subspace Stabilizer"
            ],
            correctAnswer: 2,
            explanation: "Antimatter is stored safely in magnetic pods at the base and injected upwards through the Lower Antimatter Injector to meet the matter stream exactly in the center."
        },
        {
            question: "What system is responsible for extracting the generated energy to power the ship?",
            options: [
                "EPS Power Tap Assembly",
                "Deuterium Flow Valves",
                "Isomagnetic Regulators",
                "Warp Core Ejection Port"
            ],
            correctAnswer: 0,
            explanation: "The Electro-Plasma System (EPS) Tap Assembly siphons off the highly energetic plasma generated in the core and distributes it through conduits to the warp nacelles."
        }
    ];

    return {
        group,
        parts,
        description,
        quizQuestions,
        animate
    };
}

// Auto-generated missing stub
export function createWarpCore() {
    const group = new THREE.Group();
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial({color: 0xff0000}));
    group.add(mesh);
    return group;
}
